// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/opencrafts-io/verisafe/internal/repository (interfaces: Querier)
//
// Generated by this command:
//
//	mockgen -package mockQuerier -destination internal/repository/mocks/mock_querier.go github.com/opencrafts-io/verisafe/internal/repository Querier
//

// Package mockQuerier is a generated GoMock package.
package mockQuerier

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	repository "github.com/opencrafts-io/verisafe/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// AddAccountInstitution mocks base method.
func (m *MockQuerier) AddAccountInstitution(ctx context.Context, arg repository.AddAccountInstitutionParams) (repository.AddAccountInstitutionRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAccountInstitution", ctx, arg)
	ret0, _ := ret[0].(repository.AddAccountInstitutionRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddAccountInstitution indicates an expected call of AddAccountInstitution.
func (mr *MockQuerierMockRecorder) AddAccountInstitution(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAccountInstitution", reflect.TypeOf((*MockQuerier)(nil).AddAccountInstitution), ctx, arg)
}

// AssignRole mocks base method.
func (m *MockQuerier) AssignRole(ctx context.Context, arg repository.AssignRoleParams) (repository.UserRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignRole", ctx, arg)
	ret0, _ := ret[0].(repository.UserRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssignRole indicates an expected call of AssignRole.
func (mr *MockQuerierMockRecorder) AssignRole(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignRole", reflect.TypeOf((*MockQuerier)(nil).AssignRole), ctx, arg)
}

// AssignRolePermission mocks base method.
func (m *MockQuerier) AssignRolePermission(ctx context.Context, arg repository.AssignRolePermissionParams) (repository.RolePermission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignRolePermission", ctx, arg)
	ret0, _ := ret[0].(repository.RolePermission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssignRolePermission indicates an expected call of AssignRolePermission.
func (mr *MockQuerierMockRecorder) AssignRolePermission(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignRolePermission", reflect.TypeOf((*MockQuerier)(nil).AssignRolePermission), ctx, arg)
}

// CleanupExpiredServiceTokens mocks base method.
func (m *MockQuerier) CleanupExpiredServiceTokens(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupExpiredServiceTokens", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanupExpiredServiceTokens indicates an expected call of CleanupExpiredServiceTokens.
func (mr *MockQuerierMockRecorder) CleanupExpiredServiceTokens(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupExpiredServiceTokens", reflect.TypeOf((*MockQuerier)(nil).CleanupExpiredServiceTokens), ctx)
}

// CreateAccount mocks base method.
func (m *MockQuerier) CreateAccount(ctx context.Context, arg repository.CreateAccountParams) (repository.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccount", ctx, arg)
	ret0, _ := ret[0].(repository.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccount indicates an expected call of CreateAccount.
func (mr *MockQuerierMockRecorder) CreateAccount(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockQuerier)(nil).CreateAccount), ctx, arg)
}

// CreateActivity mocks base method.
func (m *MockQuerier) CreateActivity(ctx context.Context, arg repository.CreateActivityParams) (repository.Activity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateActivity", ctx, arg)
	ret0, _ := ret[0].(repository.Activity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateActivity indicates an expected call of CreateActivity.
func (mr *MockQuerierMockRecorder) CreateActivity(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateActivity", reflect.TypeOf((*MockQuerier)(nil).CreateActivity), ctx, arg)
}

// CreateInstitution mocks base method.
func (m *MockQuerier) CreateInstitution(ctx context.Context, arg repository.CreateInstitutionParams) (repository.Institution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInstitution", ctx, arg)
	ret0, _ := ret[0].(repository.Institution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInstitution indicates an expected call of CreateInstitution.
func (mr *MockQuerierMockRecorder) CreateInstitution(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInstitution", reflect.TypeOf((*MockQuerier)(nil).CreateInstitution), ctx, arg)
}

// CreatePermission mocks base method.
func (m *MockQuerier) CreatePermission(ctx context.Context, arg repository.CreatePermissionParams) (repository.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePermission", ctx, arg)
	ret0, _ := ret[0].(repository.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePermission indicates an expected call of CreatePermission.
func (mr *MockQuerierMockRecorder) CreatePermission(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePermission", reflect.TypeOf((*MockQuerier)(nil).CreatePermission), ctx, arg)
}

// CreateRole mocks base method.
func (m *MockQuerier) CreateRole(ctx context.Context, arg repository.CreateRoleParams) (repository.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRole", ctx, arg)
	ret0, _ := ret[0].(repository.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRole indicates an expected call of CreateRole.
func (mr *MockQuerierMockRecorder) CreateRole(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRole", reflect.TypeOf((*MockQuerier)(nil).CreateRole), ctx, arg)
}

// CreateServiceToken mocks base method.
func (m *MockQuerier) CreateServiceToken(ctx context.Context, arg repository.CreateServiceTokenParams) (repository.ServiceToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateServiceToken", ctx, arg)
	ret0, _ := ret[0].(repository.ServiceToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateServiceToken indicates an expected call of CreateServiceToken.
func (mr *MockQuerierMockRecorder) CreateServiceToken(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateServiceToken", reflect.TypeOf((*MockQuerier)(nil).CreateServiceToken), ctx, arg)
}

// CreateSocial mocks base method.
func (m *MockQuerier) CreateSocial(ctx context.Context, arg repository.CreateSocialParams) (repository.Social, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSocial", ctx, arg)
	ret0, _ := ret[0].(repository.Social)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSocial indicates an expected call of CreateSocial.
func (mr *MockQuerierMockRecorder) CreateSocial(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSocial", reflect.TypeOf((*MockQuerier)(nil).CreateSocial), ctx, arg)
}

// CreateStreakMilestone mocks base method.
func (m *MockQuerier) CreateStreakMilestone(ctx context.Context, arg repository.CreateStreakMilestoneParams) (repository.StreakMilestone, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStreakMilestone", ctx, arg)
	ret0, _ := ret[0].(repository.StreakMilestone)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStreakMilestone indicates an expected call of CreateStreakMilestone.
func (mr *MockQuerierMockRecorder) CreateStreakMilestone(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStreakMilestone", reflect.TypeOf((*MockQuerier)(nil).CreateStreakMilestone), ctx, arg)
}

// DeleteActivity mocks base method.
func (m *MockQuerier) DeleteActivity(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteActivity", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteActivity indicates an expected call of DeleteActivity.
func (mr *MockQuerierMockRecorder) DeleteActivity(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteActivity", reflect.TypeOf((*MockQuerier)(nil).DeleteActivity), ctx, id)
}

// DeleteInstitution mocks base method.
func (m *MockQuerier) DeleteInstitution(ctx context.Context, institutionID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInstitution", ctx, institutionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInstitution indicates an expected call of DeleteInstitution.
func (mr *MockQuerierMockRecorder) DeleteInstitution(ctx, institutionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInstitution", reflect.TypeOf((*MockQuerier)(nil).DeleteInstitution), ctx, institutionID)
}

// DeleteServiceToken mocks base method.
func (m *MockQuerier) DeleteServiceToken(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteServiceToken", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteServiceToken indicates an expected call of DeleteServiceToken.
func (mr *MockQuerierMockRecorder) DeleteServiceToken(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteServiceToken", reflect.TypeOf((*MockQuerier)(nil).DeleteServiceToken), ctx, id)
}

// DeleteStreakMilestoneByID mocks base method.
func (m *MockQuerier) DeleteStreakMilestoneByID(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStreakMilestoneByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStreakMilestoneByID indicates an expected call of DeleteStreakMilestoneByID.
func (mr *MockQuerierMockRecorder) DeleteStreakMilestoneByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStreakMilestoneByID", reflect.TypeOf((*MockQuerier)(nil).DeleteStreakMilestoneByID), ctx, id)
}

// GetAccountByEmail mocks base method.
func (m *MockQuerier) GetAccountByEmail(ctx context.Context, email string) (repository.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountByEmail", ctx, email)
	ret0, _ := ret[0].(repository.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountByEmail indicates an expected call of GetAccountByEmail.
func (mr *MockQuerierMockRecorder) GetAccountByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountByEmail", reflect.TypeOf((*MockQuerier)(nil).GetAccountByEmail), ctx, email)
}

// GetAccountByID mocks base method.
func (m *MockQuerier) GetAccountByID(ctx context.Context, id uuid.UUID) (repository.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountByID", ctx, id)
	ret0, _ := ret[0].(repository.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountByID indicates an expected call of GetAccountByID.
func (mr *MockQuerierMockRecorder) GetAccountByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountByID", reflect.TypeOf((*MockQuerier)(nil).GetAccountByID), ctx, id)
}

// GetAccountByProvider mocks base method.
func (m *MockQuerier) GetAccountByProvider(ctx context.Context, arg repository.GetAccountByProviderParams) ([]repository.Social, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountByProvider", ctx, arg)
	ret0, _ := ret[0].([]repository.Social)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountByProvider indicates an expected call of GetAccountByProvider.
func (mr *MockQuerierMockRecorder) GetAccountByProvider(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountByProvider", reflect.TypeOf((*MockQuerier)(nil).GetAccountByProvider), ctx, arg)
}

// GetAccountByUsername mocks base method.
func (m *MockQuerier) GetAccountByUsername(ctx context.Context, username string) (repository.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountByUsername", ctx, username)
	ret0, _ := ret[0].(repository.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountByUsername indicates an expected call of GetAccountByUsername.
func (mr *MockQuerierMockRecorder) GetAccountByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountByUsername", reflect.TypeOf((*MockQuerier)(nil).GetAccountByUsername), ctx, username)
}

// GetAccountsCount mocks base method.
func (m *MockQuerier) GetAccountsCount(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountsCount", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountsCount indicates an expected call of GetAccountsCount.
func (mr *MockQuerierMockRecorder) GetAccountsCount(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountsCount", reflect.TypeOf((*MockQuerier)(nil).GetAccountsCount), ctx)
}

// GetActivityByID mocks base method.
func (m *MockQuerier) GetActivityByID(ctx context.Context, id uuid.UUID) (repository.Activity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActivityByID", ctx, id)
	ret0, _ := ret[0].(repository.Activity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActivityByID indicates an expected call of GetActivityByID.
func (mr *MockQuerierMockRecorder) GetActivityByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActivityByID", reflect.TypeOf((*MockQuerier)(nil).GetActivityByID), ctx, id)
}

// GetAllAccountSocials mocks base method.
func (m *MockQuerier) GetAllAccountSocials(ctx context.Context, accountID uuid.UUID) ([]repository.Social, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllAccountSocials", ctx, accountID)
	ret0, _ := ret[0].([]repository.Social)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllAccountSocials indicates an expected call of GetAllAccountSocials.
func (mr *MockQuerierMockRecorder) GetAllAccountSocials(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllAccountSocials", reflect.TypeOf((*MockQuerier)(nil).GetAllAccountSocials), ctx, accountID)
}

// GetAllAccounts mocks base method.
func (m *MockQuerier) GetAllAccounts(ctx context.Context, arg repository.GetAllAccountsParams) ([]repository.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllAccounts", ctx, arg)
	ret0, _ := ret[0].([]repository.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllAccounts indicates an expected call of GetAllAccounts.
func (mr *MockQuerierMockRecorder) GetAllAccounts(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllAccounts", reflect.TypeOf((*MockQuerier)(nil).GetAllAccounts), ctx, arg)
}

// GetAllActiveActivities mocks base method.
func (m *MockQuerier) GetAllActiveActivities(ctx context.Context, arg repository.GetAllActiveActivitiesParams) ([]repository.Activity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllActiveActivities", ctx, arg)
	ret0, _ := ret[0].([]repository.Activity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllActiveActivities indicates an expected call of GetAllActiveActivities.
func (mr *MockQuerierMockRecorder) GetAllActiveActivities(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllActiveActivities", reflect.TypeOf((*MockQuerier)(nil).GetAllActiveActivities), ctx, arg)
}

// GetAllActiveActivitiesCount mocks base method.
func (m *MockQuerier) GetAllActiveActivitiesCount(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllActiveActivitiesCount", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllActiveActivitiesCount indicates an expected call of GetAllActiveActivitiesCount.
func (mr *MockQuerierMockRecorder) GetAllActiveActivitiesCount(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllActiveActivitiesCount", reflect.TypeOf((*MockQuerier)(nil).GetAllActiveActivitiesCount), ctx)
}

// GetAllActiveStreakMilestoneCount mocks base method.
func (m *MockQuerier) GetAllActiveStreakMilestoneCount(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllActiveStreakMilestoneCount", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllActiveStreakMilestoneCount indicates an expected call of GetAllActiveStreakMilestoneCount.
func (mr *MockQuerierMockRecorder) GetAllActiveStreakMilestoneCount(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllActiveStreakMilestoneCount", reflect.TypeOf((*MockQuerier)(nil).GetAllActiveStreakMilestoneCount), ctx)
}

// GetAllActivities mocks base method.
func (m *MockQuerier) GetAllActivities(ctx context.Context, arg repository.GetAllActivitiesParams) ([]repository.Activity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllActivities", ctx, arg)
	ret0, _ := ret[0].([]repository.Activity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllActivities indicates an expected call of GetAllActivities.
func (mr *MockQuerierMockRecorder) GetAllActivities(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllActivities", reflect.TypeOf((*MockQuerier)(nil).GetAllActivities), ctx, arg)
}

// GetAllActivitiesCount mocks base method.
func (m *MockQuerier) GetAllActivitiesCount(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllActivitiesCount", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllActivitiesCount indicates an expected call of GetAllActivitiesCount.
func (mr *MockQuerierMockRecorder) GetAllActivitiesCount(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllActivitiesCount", reflect.TypeOf((*MockQuerier)(nil).GetAllActivitiesCount), ctx)
}

// GetAllInactiveActivities mocks base method.
func (m *MockQuerier) GetAllInactiveActivities(ctx context.Context, arg repository.GetAllInactiveActivitiesParams) ([]repository.Activity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllInactiveActivities", ctx, arg)
	ret0, _ := ret[0].([]repository.Activity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllInactiveActivities indicates an expected call of GetAllInactiveActivities.
func (mr *MockQuerierMockRecorder) GetAllInactiveActivities(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllInactiveActivities", reflect.TypeOf((*MockQuerier)(nil).GetAllInactiveActivities), ctx, arg)
}

// GetAllInactiveActivitiesCount mocks base method.
func (m *MockQuerier) GetAllInactiveActivitiesCount(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllInactiveActivitiesCount", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllInactiveActivitiesCount indicates an expected call of GetAllInactiveActivitiesCount.
func (mr *MockQuerierMockRecorder) GetAllInactiveActivitiesCount(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllInactiveActivitiesCount", reflect.TypeOf((*MockQuerier)(nil).GetAllInactiveActivitiesCount), ctx)
}

// GetAllInactiveStreakMilestoneCount mocks base method.
func (m *MockQuerier) GetAllInactiveStreakMilestoneCount(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllInactiveStreakMilestoneCount", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllInactiveStreakMilestoneCount indicates an expected call of GetAllInactiveStreakMilestoneCount.
func (mr *MockQuerierMockRecorder) GetAllInactiveStreakMilestoneCount(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllInactiveStreakMilestoneCount", reflect.TypeOf((*MockQuerier)(nil).GetAllInactiveStreakMilestoneCount), ctx)
}

// GetAllPermissions mocks base method.
func (m *MockQuerier) GetAllPermissions(ctx context.Context, arg repository.GetAllPermissionsParams) ([]repository.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPermissions", ctx, arg)
	ret0, _ := ret[0].([]repository.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllPermissions indicates an expected call of GetAllPermissions.
func (mr *MockQuerierMockRecorder) GetAllPermissions(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPermissions", reflect.TypeOf((*MockQuerier)(nil).GetAllPermissions), ctx, arg)
}

// GetAllRoles mocks base method.
func (m *MockQuerier) GetAllRoles(ctx context.Context, arg repository.GetAllRolesParams) ([]repository.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllRoles", ctx, arg)
	ret0, _ := ret[0].([]repository.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllRoles indicates an expected call of GetAllRoles.
func (mr *MockQuerierMockRecorder) GetAllRoles(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllRoles", reflect.TypeOf((*MockQuerier)(nil).GetAllRoles), ctx, arg)
}

// GetAllStreaksMilestoneByActive mocks base method.
func (m *MockQuerier) GetAllStreaksMilestoneByActive(ctx context.Context, arg repository.GetAllStreaksMilestoneByActiveParams) ([]repository.StreakMilestone, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllStreaksMilestoneByActive", ctx, arg)
	ret0, _ := ret[0].([]repository.StreakMilestone)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllStreaksMilestoneByActive indicates an expected call of GetAllStreaksMilestoneByActive.
func (mr *MockQuerierMockRecorder) GetAllStreaksMilestoneByActive(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllStreaksMilestoneByActive", reflect.TypeOf((*MockQuerier)(nil).GetAllStreaksMilestoneByActive), ctx, arg)
}

// GetAllUserActivityCompletions mocks base method.
func (m *MockQuerier) GetAllUserActivityCompletions(ctx context.Context, arg repository.GetAllUserActivityCompletionsParams) ([]repository.ActivityCompletion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUserActivityCompletions", ctx, arg)
	ret0, _ := ret[0].([]repository.ActivityCompletion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllUserActivityCompletions indicates an expected call of GetAllUserActivityCompletions.
func (mr *MockQuerierMockRecorder) GetAllUserActivityCompletions(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUserActivityCompletions", reflect.TypeOf((*MockQuerier)(nil).GetAllUserActivityCompletions), ctx, arg)
}

// GetAllUserActivityCompletionsCount mocks base method.
func (m *MockQuerier) GetAllUserActivityCompletionsCount(ctx context.Context, accountID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUserActivityCompletionsCount", ctx, accountID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllUserActivityCompletionsCount indicates an expected call of GetAllUserActivityCompletionsCount.
func (mr *MockQuerierMockRecorder) GetAllUserActivityCompletionsCount(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUserActivityCompletionsCount", reflect.TypeOf((*MockQuerier)(nil).GetAllUserActivityCompletionsCount), ctx, accountID)
}

// GetAllUserRoleNames mocks base method.
func (m *MockQuerier) GetAllUserRoleNames(ctx context.Context, userID uuid.UUID) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUserRoleNames", ctx, userID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllUserRoleNames indicates an expected call of GetAllUserRoleNames.
func (mr *MockQuerierMockRecorder) GetAllUserRoleNames(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUserRoleNames", reflect.TypeOf((*MockQuerier)(nil).GetAllUserRoleNames), ctx, userID)
}

// GetAllUserRoles mocks base method.
func (m *MockQuerier) GetAllUserRoles(ctx context.Context, userID uuid.UUID) ([]repository.UserRolesView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUserRoles", ctx, userID)
	ret0, _ := ret[0].([]repository.UserRolesView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllUserRoles indicates an expected call of GetAllUserRoles.
func (mr *MockQuerierMockRecorder) GetAllUserRoles(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUserRoles", reflect.TypeOf((*MockQuerier)(nil).GetAllUserRoles), ctx, userID)
}

// GetGlobalLeaderBoardCount mocks base method.
func (m *MockQuerier) GetGlobalLeaderBoardCount(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGlobalLeaderBoardCount", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGlobalLeaderBoardCount indicates an expected call of GetGlobalLeaderBoardCount.
func (mr *MockQuerierMockRecorder) GetGlobalLeaderBoardCount(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGlobalLeaderBoardCount", reflect.TypeOf((*MockQuerier)(nil).GetGlobalLeaderBoardCount), ctx)
}

// GetInstitution mocks base method.
func (m *MockQuerier) GetInstitution(ctx context.Context, institutionID int32) (repository.Institution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstitution", ctx, institutionID)
	ret0, _ := ret[0].(repository.Institution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstitution indicates an expected call of GetInstitution.
func (mr *MockQuerierMockRecorder) GetInstitution(ctx, institutionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstitution", reflect.TypeOf((*MockQuerier)(nil).GetInstitution), ctx, institutionID)
}

// GetInstitutionsCount mocks base method.
func (m *MockQuerier) GetInstitutionsCount(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstitutionsCount", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstitutionsCount indicates an expected call of GetInstitutionsCount.
func (mr *MockQuerierMockRecorder) GetInstitutionsCount(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstitutionsCount", reflect.TypeOf((*MockQuerier)(nil).GetInstitutionsCount), ctx)
}

// GetLeaderBoardRankForUser mocks base method.
func (m *MockQuerier) GetLeaderBoardRankForUser(ctx context.Context, id uuid.UUID) (repository.AccountVibepointRank, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLeaderBoardRankForUser", ctx, id)
	ret0, _ := ret[0].(repository.AccountVibepointRank)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLeaderBoardRankForUser indicates an expected call of GetLeaderBoardRankForUser.
func (mr *MockQuerierMockRecorder) GetLeaderBoardRankForUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLeaderBoardRankForUser", reflect.TypeOf((*MockQuerier)(nil).GetLeaderBoardRankForUser), ctx, id)
}

// GetLeaderboard mocks base method.
func (m *MockQuerier) GetLeaderboard(ctx context.Context, arg repository.GetLeaderboardParams) ([]repository.AccountVibepointRank, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLeaderboard", ctx, arg)
	ret0, _ := ret[0].([]repository.AccountVibepointRank)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLeaderboard indicates an expected call of GetLeaderboard.
func (mr *MockQuerierMockRecorder) GetLeaderboard(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLeaderboard", reflect.TypeOf((*MockQuerier)(nil).GetLeaderboard), ctx, arg)
}

// GetPermissionByID mocks base method.
func (m *MockQuerier) GetPermissionByID(ctx context.Context, id uuid.UUID) ([]repository.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPermissionByID", ctx, id)
	ret0, _ := ret[0].([]repository.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPermissionByID indicates an expected call of GetPermissionByID.
func (mr *MockQuerierMockRecorder) GetPermissionByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermissionByID", reflect.TypeOf((*MockQuerier)(nil).GetPermissionByID), ctx, id)
}

// GetRoleByID mocks base method.
func (m *MockQuerier) GetRoleByID(ctx context.Context, id uuid.UUID) (repository.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoleByID", ctx, id)
	ret0, _ := ret[0].(repository.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoleByID indicates an expected call of GetRoleByID.
func (mr *MockQuerierMockRecorder) GetRoleByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoleByID", reflect.TypeOf((*MockQuerier)(nil).GetRoleByID), ctx, id)
}

// GetRoleByName mocks base method.
func (m *MockQuerier) GetRoleByName(ctx context.Context, name string) (repository.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoleByName", ctx, name)
	ret0, _ := ret[0].(repository.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoleByName indicates an expected call of GetRoleByName.
func (mr *MockQuerierMockRecorder) GetRoleByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoleByName", reflect.TypeOf((*MockQuerier)(nil).GetRoleByName), ctx, name)
}

// GetRolePermissions mocks base method.
func (m *MockQuerier) GetRolePermissions(ctx context.Context, roleID uuid.UUID) ([]repository.RolePermissionsView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRolePermissions", ctx, roleID)
	ret0, _ := ret[0].([]repository.RolePermissionsView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRolePermissions indicates an expected call of GetRolePermissions.
func (mr *MockQuerierMockRecorder) GetRolePermissions(ctx, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRolePermissions", reflect.TypeOf((*MockQuerier)(nil).GetRolePermissions), ctx, roleID)
}

// GetServiceTokenByHash mocks base method.
func (m *MockQuerier) GetServiceTokenByHash(ctx context.Context, tokenHash string) (repository.ServiceToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceTokenByHash", ctx, tokenHash)
	ret0, _ := ret[0].(repository.ServiceToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceTokenByHash indicates an expected call of GetServiceTokenByHash.
func (mr *MockQuerierMockRecorder) GetServiceTokenByHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceTokenByHash", reflect.TypeOf((*MockQuerier)(nil).GetServiceTokenByHash), ctx, tokenHash)
}

// GetServiceTokenByID mocks base method.
func (m *MockQuerier) GetServiceTokenByID(ctx context.Context, id uuid.UUID) (repository.ServiceToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceTokenByID", ctx, id)
	ret0, _ := ret[0].(repository.ServiceToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceTokenByID indicates an expected call of GetServiceTokenByID.
func (mr *MockQuerierMockRecorder) GetServiceTokenByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceTokenByID", reflect.TypeOf((*MockQuerier)(nil).GetServiceTokenByID), ctx, id)
}

// GetServiceTokenUsageStats mocks base method.
func (m *MockQuerier) GetServiceTokenUsageStats(ctx context.Context, accountID uuid.UUID) (repository.GetServiceTokenUsageStatsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceTokenUsageStats", ctx, accountID)
	ret0, _ := ret[0].(repository.GetServiceTokenUsageStatsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceTokenUsageStats indicates an expected call of GetServiceTokenUsageStats.
func (mr *MockQuerierMockRecorder) GetServiceTokenUsageStats(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceTokenUsageStats", reflect.TypeOf((*MockQuerier)(nil).GetServiceTokenUsageStats), ctx, accountID)
}

// GetSocialByExternalUserID mocks base method.
func (m *MockQuerier) GetSocialByExternalUserID(ctx context.Context, userID string) (repository.Social, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSocialByExternalUserID", ctx, userID)
	ret0, _ := ret[0].(repository.Social)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSocialByExternalUserID indicates an expected call of GetSocialByExternalUserID.
func (mr *MockQuerierMockRecorder) GetSocialByExternalUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSocialByExternalUserID", reflect.TypeOf((*MockQuerier)(nil).GetSocialByExternalUserID), ctx, userID)
}

// GetUserDevices mocks base method.
func (m *MockQuerier) GetUserDevices(ctx context.Context, userID uuid.UUID) ([]repository.UserDevice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserDevices", ctx, userID)
	ret0, _ := ret[0].([]repository.UserDevice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserDevices indicates an expected call of GetUserDevices.
func (mr *MockQuerierMockRecorder) GetUserDevices(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserDevices", reflect.TypeOf((*MockQuerier)(nil).GetUserDevices), ctx, userID)
}

// GetUserPermissionNames mocks base method.
func (m *MockQuerier) GetUserPermissionNames(ctx context.Context, userID uuid.UUID) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPermissionNames", ctx, userID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserPermissionNames indicates an expected call of GetUserPermissionNames.
func (mr *MockQuerierMockRecorder) GetUserPermissionNames(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPermissionNames", reflect.TypeOf((*MockQuerier)(nil).GetUserPermissionNames), ctx, userID)
}

// GetUserPermissions mocks base method.
func (m *MockQuerier) GetUserPermissions(ctx context.Context, userID uuid.UUID) ([]repository.UserPermissionsView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPermissions", ctx, userID)
	ret0, _ := ret[0].([]repository.UserPermissionsView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserPermissions indicates an expected call of GetUserPermissions.
func (mr *MockQuerierMockRecorder) GetUserPermissions(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPermissions", reflect.TypeOf((*MockQuerier)(nil).GetUserPermissions), ctx, userID)
}

// GetUserStreaks mocks base method.
func (m *MockQuerier) GetUserStreaks(ctx context.Context, accountID uuid.UUID) ([]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserStreaks", ctx, accountID)
	ret0, _ := ret[0].([]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserStreaks indicates an expected call of GetUserStreaks.
func (mr *MockQuerierMockRecorder) GetUserStreaks(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserStreaks", reflect.TypeOf((*MockQuerier)(nil).GetUserStreaks), ctx, accountID)
}

// ListAccountsForInstitution mocks base method.
func (m *MockQuerier) ListAccountsForInstitution(ctx context.Context, arg repository.ListAccountsForInstitutionParams) ([]repository.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccountsForInstitution", ctx, arg)
	ret0, _ := ret[0].([]repository.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAccountsForInstitution indicates an expected call of ListAccountsForInstitution.
func (mr *MockQuerierMockRecorder) ListAccountsForInstitution(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccountsForInstitution", reflect.TypeOf((*MockQuerier)(nil).ListAccountsForInstitution), ctx, arg)
}

// ListActiveServiceTokens mocks base method.
func (m *MockQuerier) ListActiveServiceTokens(ctx context.Context) ([]repository.ActiveServiceToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveServiceTokens", ctx)
	ret0, _ := ret[0].([]repository.ActiveServiceToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActiveServiceTokens indicates an expected call of ListActiveServiceTokens.
func (mr *MockQuerierMockRecorder) ListActiveServiceTokens(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveServiceTokens", reflect.TypeOf((*MockQuerier)(nil).ListActiveServiceTokens), ctx)
}

// ListInstitutions mocks base method.
func (m *MockQuerier) ListInstitutions(ctx context.Context, arg repository.ListInstitutionsParams) ([]repository.Institution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInstitutions", ctx, arg)
	ret0, _ := ret[0].([]repository.Institution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInstitutions indicates an expected call of ListInstitutions.
func (mr *MockQuerierMockRecorder) ListInstitutions(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInstitutions", reflect.TypeOf((*MockQuerier)(nil).ListInstitutions), ctx, arg)
}

// ListInstitutionsForAccount mocks base method.
func (m *MockQuerier) ListInstitutionsForAccount(ctx context.Context, arg repository.ListInstitutionsForAccountParams) ([]repository.Institution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInstitutionsForAccount", ctx, arg)
	ret0, _ := ret[0].([]repository.Institution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInstitutionsForAccount indicates an expected call of ListInstitutionsForAccount.
func (mr *MockQuerierMockRecorder) ListInstitutionsForAccount(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInstitutionsForAccount", reflect.TypeOf((*MockQuerier)(nil).ListInstitutionsForAccount), ctx, arg)
}

// ListServiceTokensByAccount mocks base method.
func (m *MockQuerier) ListServiceTokensByAccount(ctx context.Context, accountID uuid.UUID) ([]repository.ServiceToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListServiceTokensByAccount", ctx, accountID)
	ret0, _ := ret[0].([]repository.ServiceToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListServiceTokensByAccount indicates an expected call of ListServiceTokensByAccount.
func (mr *MockQuerierMockRecorder) ListServiceTokensByAccount(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListServiceTokensByAccount", reflect.TypeOf((*MockQuerier)(nil).ListServiceTokensByAccount), ctx, accountID)
}

// ListServiceTokensNeedingRotation mocks base method.
func (m *MockQuerier) ListServiceTokensNeedingRotation(ctx context.Context) ([]repository.ServiceToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListServiceTokensNeedingRotation", ctx)
	ret0, _ := ret[0].([]repository.ServiceToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListServiceTokensNeedingRotation indicates an expected call of ListServiceTokensNeedingRotation.
func (mr *MockQuerierMockRecorder) ListServiceTokensNeedingRotation(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListServiceTokensNeedingRotation", reflect.TypeOf((*MockQuerier)(nil).ListServiceTokensNeedingRotation), ctx)
}

// MarkAccountForDeletion mocks base method.
func (m *MockQuerier) MarkAccountForDeletion(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAccountForDeletion", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAccountForDeletion indicates an expected call of MarkAccountForDeletion.
func (mr *MockQuerierMockRecorder) MarkAccountForDeletion(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAccountForDeletion", reflect.TypeOf((*MockQuerier)(nil).MarkAccountForDeletion), ctx, id)
}

// MarkAccountForRecovery mocks base method.
func (m *MockQuerier) MarkAccountForRecovery(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAccountForRecovery", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAccountForRecovery indicates an expected call of MarkAccountForRecovery.
func (mr *MockQuerierMockRecorder) MarkAccountForRecovery(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAccountForRecovery", reflect.TypeOf((*MockQuerier)(nil).MarkAccountForRecovery), ctx, id)
}

// MarkTokensForRotation mocks base method.
func (m *MockQuerier) MarkTokensForRotation(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkTokensForRotation", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkTokensForRotation indicates an expected call of MarkTokensForRotation.
func (mr *MockQuerierMockRecorder) MarkTokensForRotation(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkTokensForRotation", reflect.TypeOf((*MockQuerier)(nil).MarkTokensForRotation), ctx)
}

// RecordActivityCompletion mocks base method.
func (m *MockQuerier) RecordActivityCompletion(ctx context.Context, arg repository.RecordActivityCompletionParams) (repository.RecordActivityCompletionRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordActivityCompletion", ctx, arg)
	ret0, _ := ret[0].(repository.RecordActivityCompletionRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecordActivityCompletion indicates an expected call of RecordActivityCompletion.
func (mr *MockQuerierMockRecorder) RecordActivityCompletion(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordActivityCompletion", reflect.TypeOf((*MockQuerier)(nil).RecordActivityCompletion), ctx, arg)
}

// RecordIssuedRefreshToken mocks base method.
func (m *MockQuerier) RecordIssuedRefreshToken(ctx context.Context, arg repository.RecordIssuedRefreshTokenParams) (repository.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordIssuedRefreshToken", ctx, arg)
	ret0, _ := ret[0].(repository.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecordIssuedRefreshToken indicates an expected call of RecordIssuedRefreshToken.
func (mr *MockQuerierMockRecorder) RecordIssuedRefreshToken(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordIssuedRefreshToken", reflect.TypeOf((*MockQuerier)(nil).RecordIssuedRefreshToken), ctx, arg)
}

// RecordIssuedToken mocks base method.
func (m *MockQuerier) RecordIssuedToken(ctx context.Context, arg repository.RecordIssuedTokenParams) (repository.IssuedToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordIssuedToken", ctx, arg)
	ret0, _ := ret[0].(repository.IssuedToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecordIssuedToken indicates an expected call of RecordIssuedToken.
func (mr *MockQuerierMockRecorder) RecordIssuedToken(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordIssuedToken", reflect.TypeOf((*MockQuerier)(nil).RecordIssuedToken), ctx, arg)
}

// RecordUserDevice mocks base method.
func (m *MockQuerier) RecordUserDevice(ctx context.Context, arg repository.RecordUserDeviceParams) (repository.UserDevice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordUserDevice", ctx, arg)
	ret0, _ := ret[0].(repository.UserDevice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecordUserDevice indicates an expected call of RecordUserDevice.
func (mr *MockQuerierMockRecorder) RecordUserDevice(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordUserDevice", reflect.TypeOf((*MockQuerier)(nil).RecordUserDevice), ctx, arg)
}

// RemoveAccountInstitution mocks base method.
func (m *MockQuerier) RemoveAccountInstitution(ctx context.Context, arg repository.RemoveAccountInstitutionParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAccountInstitution", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAccountInstitution indicates an expected call of RemoveAccountInstitution.
func (mr *MockQuerierMockRecorder) RemoveAccountInstitution(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAccountInstitution", reflect.TypeOf((*MockQuerier)(nil).RemoveAccountInstitution), ctx, arg)
}

// RevokeRole mocks base method.
func (m *MockQuerier) RevokeRole(ctx context.Context, arg repository.RevokeRoleParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeRole", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeRole indicates an expected call of RevokeRole.
func (mr *MockQuerierMockRecorder) RevokeRole(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeRole", reflect.TypeOf((*MockQuerier)(nil).RevokeRole), ctx, arg)
}

// RevokeRolePermission mocks base method.
func (m *MockQuerier) RevokeRolePermission(ctx context.Context, arg repository.RevokeRolePermissionParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeRolePermission", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeRolePermission indicates an expected call of RevokeRolePermission.
func (mr *MockQuerierMockRecorder) RevokeRolePermission(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeRolePermission", reflect.TypeOf((*MockQuerier)(nil).RevokeRolePermission), ctx, arg)
}

// RevokeServiceToken mocks base method.
func (m *MockQuerier) RevokeServiceToken(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeServiceToken", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeServiceToken indicates an expected call of RevokeServiceToken.
func (mr *MockQuerierMockRecorder) RevokeServiceToken(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeServiceToken", reflect.TypeOf((*MockQuerier)(nil).RevokeServiceToken), ctx, id)
}

// RotateServiceToken mocks base method.
func (m *MockQuerier) RotateServiceToken(ctx context.Context, arg repository.RotateServiceTokenParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RotateServiceToken", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// RotateServiceToken indicates an expected call of RotateServiceToken.
func (mr *MockQuerierMockRecorder) RotateServiceToken(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RotateServiceToken", reflect.TypeOf((*MockQuerier)(nil).RotateServiceToken), ctx, arg)
}

// SearchAccountByEmail mocks base method.
func (m *MockQuerier) SearchAccountByEmail(ctx context.Context, arg repository.SearchAccountByEmailParams) ([]repository.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchAccountByEmail", ctx, arg)
	ret0, _ := ret[0].([]repository.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchAccountByEmail indicates an expected call of SearchAccountByEmail.
func (mr *MockQuerierMockRecorder) SearchAccountByEmail(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchAccountByEmail", reflect.TypeOf((*MockQuerier)(nil).SearchAccountByEmail), ctx, arg)
}

// SearchAccountByName mocks base method.
func (m *MockQuerier) SearchAccountByName(ctx context.Context, arg repository.SearchAccountByNameParams) ([]repository.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchAccountByName", ctx, arg)
	ret0, _ := ret[0].([]repository.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchAccountByName indicates an expected call of SearchAccountByName.
func (mr *MockQuerierMockRecorder) SearchAccountByName(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchAccountByName", reflect.TypeOf((*MockQuerier)(nil).SearchAccountByName), ctx, arg)
}

// SearchAccountByUsername mocks base method.
func (m *MockQuerier) SearchAccountByUsername(ctx context.Context, arg repository.SearchAccountByUsernameParams) ([]repository.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchAccountByUsername", ctx, arg)
	ret0, _ := ret[0].([]repository.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchAccountByUsername indicates an expected call of SearchAccountByUsername.
func (mr *MockQuerierMockRecorder) SearchAccountByUsername(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchAccountByUsername", reflect.TypeOf((*MockQuerier)(nil).SearchAccountByUsername), ctx, arg)
}

// SearchInstitutionsByName mocks base method.
func (m *MockQuerier) SearchInstitutionsByName(ctx context.Context, arg repository.SearchInstitutionsByNameParams) ([]repository.Institution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchInstitutionsByName", ctx, arg)
	ret0, _ := ret[0].([]repository.Institution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchInstitutionsByName indicates an expected call of SearchInstitutionsByName.
func (mr *MockQuerierMockRecorder) SearchInstitutionsByName(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchInstitutionsByName", reflect.TypeOf((*MockQuerier)(nil).SearchInstitutionsByName), ctx, arg)
}

// UpdateAccountDetails mocks base method.
func (m *MockQuerier) UpdateAccountDetails(ctx context.Context, arg repository.UpdateAccountDetailsParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccountDetails", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAccountDetails indicates an expected call of UpdateAccountDetails.
func (mr *MockQuerierMockRecorder) UpdateAccountDetails(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccountDetails", reflect.TypeOf((*MockQuerier)(nil).UpdateAccountDetails), ctx, arg)
}

// UpdateAccountPhoneNumber mocks base method.
func (m *MockQuerier) UpdateAccountPhoneNumber(ctx context.Context, arg repository.UpdateAccountPhoneNumberParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccountPhoneNumber", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAccountPhoneNumber indicates an expected call of UpdateAccountPhoneNumber.
func (mr *MockQuerierMockRecorder) UpdateAccountPhoneNumber(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccountPhoneNumber", reflect.TypeOf((*MockQuerier)(nil).UpdateAccountPhoneNumber), ctx, arg)
}

// UpdateActivity mocks base method.
func (m *MockQuerier) UpdateActivity(ctx context.Context, arg repository.UpdateActivityParams) (repository.Activity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateActivity", ctx, arg)
	ret0, _ := ret[0].(repository.Activity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateActivity indicates an expected call of UpdateActivity.
func (mr *MockQuerierMockRecorder) UpdateActivity(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateActivity", reflect.TypeOf((*MockQuerier)(nil).UpdateActivity), ctx, arg)
}

// UpdateInstitution mocks base method.
func (m *MockQuerier) UpdateInstitution(ctx context.Context, arg repository.UpdateInstitutionParams) (repository.Institution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInstitution", ctx, arg)
	ret0, _ := ret[0].(repository.Institution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateInstitution indicates an expected call of UpdateInstitution.
func (mr *MockQuerierMockRecorder) UpdateInstitution(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInstitution", reflect.TypeOf((*MockQuerier)(nil).UpdateInstitution), ctx, arg)
}

// UpdatePermission mocks base method.
func (m *MockQuerier) UpdatePermission(ctx context.Context, arg repository.UpdatePermissionParams) (repository.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePermission", ctx, arg)
	ret0, _ := ret[0].(repository.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePermission indicates an expected call of UpdatePermission.
func (mr *MockQuerierMockRecorder) UpdatePermission(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePermission", reflect.TypeOf((*MockQuerier)(nil).UpdatePermission), ctx, arg)
}

// UpdateRole mocks base method.
func (m *MockQuerier) UpdateRole(ctx context.Context, arg repository.UpdateRoleParams) (repository.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRole", ctx, arg)
	ret0, _ := ret[0].(repository.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRole indicates an expected call of UpdateRole.
func (mr *MockQuerierMockRecorder) UpdateRole(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRole", reflect.TypeOf((*MockQuerier)(nil).UpdateRole), ctx, arg)
}

// UpdateServiceToken mocks base method.
func (m *MockQuerier) UpdateServiceToken(ctx context.Context, arg repository.UpdateServiceTokenParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateServiceToken", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateServiceToken indicates an expected call of UpdateServiceToken.
func (mr *MockQuerierMockRecorder) UpdateServiceToken(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateServiceToken", reflect.TypeOf((*MockQuerier)(nil).UpdateServiceToken), ctx, arg)
}

// UpdateServiceTokenLastUsed mocks base method.
func (m *MockQuerier) UpdateServiceTokenLastUsed(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateServiceTokenLastUsed", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateServiceTokenLastUsed indicates an expected call of UpdateServiceTokenLastUsed.
func (mr *MockQuerierMockRecorder) UpdateServiceTokenLastUsed(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateServiceTokenLastUsed", reflect.TypeOf((*MockQuerier)(nil).UpdateServiceTokenLastUsed), ctx, id)
}

// UpdateSocial mocks base method.
func (m *MockQuerier) UpdateSocial(ctx context.Context, arg repository.UpdateSocialParams) (repository.Social, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSocial", ctx, arg)
	ret0, _ := ret[0].(repository.Social)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSocial indicates an expected call of UpdateSocial.
func (mr *MockQuerierMockRecorder) UpdateSocial(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSocial", reflect.TypeOf((*MockQuerier)(nil).UpdateSocial), ctx, arg)
}
