// Code generated by MockGen. DO NOT EDIT.
// Source: db_provider.go
//
// Generated by this command:
//
//	mockgen -source=db_provider.go -destination=mocks/db_provider.go -package=mockscore
//

// Package mockscore is a generated GoMock package.
package mockscore

import (
	context "context"
	reflect "reflect"

	pgx "github.com/jackc/pgx/v5"
	core "github.com/opencrafts-io/verisafe/internal/core"
	gomock "go.uber.org/mock/gomock"
)

// MockIDBProvider is a mock of IDBProvider interface.
type MockIDBProvider struct {
	ctrl     *gomock.Controller
	recorder *MockIDBProviderMockRecorder
	isgomock struct{}
}

// MockIDBProviderMockRecorder is the mock recorder for MockIDBProvider.
type MockIDBProviderMockRecorder struct {
	mock *MockIDBProvider
}

// NewMockIDBProvider creates a new mock instance.
func NewMockIDBProvider(ctrl *gomock.Controller) *MockIDBProvider {
	mock := &MockIDBProvider{ctrl: ctrl}
	mock.recorder = &MockIDBProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDBProvider) EXPECT() *MockIDBProviderMockRecorder {
	return m.recorder
}

// Acquire mocks base method.
func (m *MockIDBProvider) Acquire(ctx context.Context) (core.IDBConnection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Acquire", ctx)
	ret0, _ := ret[0].(core.IDBConnection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Acquire indicates an expected call of Acquire.
func (mr *MockIDBProviderMockRecorder) Acquire(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Acquire", reflect.TypeOf((*MockIDBProvider)(nil).Acquire), ctx)
}

// MockIDBConnection is a mock of IDBConnection interface.
type MockIDBConnection struct {
	ctrl     *gomock.Controller
	recorder *MockIDBConnectionMockRecorder
	isgomock struct{}
}

// MockIDBConnectionMockRecorder is the mock recorder for MockIDBConnection.
type MockIDBConnectionMockRecorder struct {
	mock *MockIDBConnection
}

// NewMockIDBConnection creates a new mock instance.
func NewMockIDBConnection(ctrl *gomock.Controller) *MockIDBConnection {
	mock := &MockIDBConnection{ctrl: ctrl}
	mock.recorder = &MockIDBConnectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDBConnection) EXPECT() *MockIDBConnectionMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockIDBConnection) Begin(ctx context.Context) (pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", ctx)
	ret0, _ := ret[0].(pgx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Begin indicates an expected call of Begin.
func (mr *MockIDBConnectionMockRecorder) Begin(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockIDBConnection)(nil).Begin), ctx)
}
