// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (email, name, type, avatar_url)
VALUES ($1, $2, $3, $4)
RETURNING id, email, name, created_at, updated_at, terms_accepted, onboarded, type, national_id, username, avatar_url, bio, vibe_points, phone
`

type CreateAccountParams struct {
	Email     string      `json:"email"`
	Name      string      `json:"name"`
	Type      AccountType `json:"type"`
	AvatarUrl *string     `json:"avatar_url"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.Email,
		arg.Name,
		arg.Type,
		arg.AvatarUrl,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TermsAccepted,
		&i.Onboarded,
		&i.Type,
		&i.NationalID,
		&i.Username,
		&i.AvatarUrl,
		&i.Bio,
		&i.VibePoints,
		&i.Phone,
	)
	return i, err
}

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT id, email, name, created_at, updated_at, terms_accepted, onboarded, type, national_id, username, avatar_url, bio, vibe_points, phone FROM accounts 
WHERE lower(email) = lower($1)
LIMIT 1
`

func (q *Queries) GetAccountByEmail(ctx context.Context, lower string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByEmail, lower)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TermsAccepted,
		&i.Onboarded,
		&i.Type,
		&i.NationalID,
		&i.Username,
		&i.AvatarUrl,
		&i.Bio,
		&i.VibePoints,
		&i.Phone,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, email, name, created_at, updated_at, terms_accepted, onboarded, type, national_id, username, avatar_url, bio, vibe_points, phone FROM accounts 
WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TermsAccepted,
		&i.Onboarded,
		&i.Type,
		&i.NationalID,
		&i.Username,
		&i.AvatarUrl,
		&i.Bio,
		&i.VibePoints,
		&i.Phone,
	)
	return i, err
}

const getAccountByUsername = `-- name: GetAccountByUsername :one
SELECT id, email, name, created_at, updated_at, terms_accepted, onboarded, type, national_id, username, avatar_url, bio, vibe_points, phone FROM accounts WHERE lower(username) = lower($1)
`

func (q *Queries) GetAccountByUsername(ctx context.Context, lower string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByUsername, lower)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TermsAccepted,
		&i.Onboarded,
		&i.Type,
		&i.NationalID,
		&i.Username,
		&i.AvatarUrl,
		&i.Bio,
		&i.VibePoints,
		&i.Phone,
	)
	return i, err
}

const getAllAccounts = `-- name: GetAllAccounts :many
SELECT id, email, name, created_at, updated_at, terms_accepted, onboarded, type, national_id, username, avatar_url, bio, vibe_points, phone FROM accounts 
LIMIT $1
OFFSET $2
`

type GetAllAccountsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAllAccounts(ctx context.Context, arg GetAllAccountsParams) ([]Account, error) {
	rows, err := q.db.Query(ctx, getAllAccounts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TermsAccepted,
			&i.Onboarded,
			&i.Type,
			&i.NationalID,
			&i.Username,
			&i.AvatarUrl,
			&i.Bio,
			&i.VibePoints,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAccountByEmail = `-- name: SearchAccountByEmail :many
SELECT id, email, name, created_at, updated_at, terms_accepted, onboarded, type, national_id, username, avatar_url, bio, vibe_points, phone FROM accounts 
WHERE lower(email) LIKE '%' || lower($1) || '%'
LIMIT $2
OFFSET $3
`

type SearchAccountByEmailParams struct {
	Lower  string `json:"lower"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) SearchAccountByEmail(ctx context.Context, arg SearchAccountByEmailParams) ([]Account, error) {
	rows, err := q.db.Query(ctx, searchAccountByEmail, arg.Lower, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TermsAccepted,
			&i.Onboarded,
			&i.Type,
			&i.NationalID,
			&i.Username,
			&i.AvatarUrl,
			&i.Bio,
			&i.VibePoints,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAccountByName = `-- name: SearchAccountByName :many
SELECT id, email, name, created_at, updated_at, terms_accepted, onboarded, type, national_id, username, avatar_url, bio, vibe_points, phone FROM accounts 
WHERE lower(name) LIKE '%' || lower($1) || '%'
LIMIT $2
OFFSET $3
`

type SearchAccountByNameParams struct {
	Lower  string `json:"lower"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) SearchAccountByName(ctx context.Context, arg SearchAccountByNameParams) ([]Account, error) {
	rows, err := q.db.Query(ctx, searchAccountByName, arg.Lower, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TermsAccepted,
			&i.Onboarded,
			&i.Type,
			&i.NationalID,
			&i.Username,
			&i.AvatarUrl,
			&i.Bio,
			&i.VibePoints,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAccountByUsername = `-- name: SearchAccountByUsername :many
SELECT id, email, name, created_at, updated_at, terms_accepted, onboarded, type, national_id, username, avatar_url, bio, vibe_points, phone FROM accounts 
WHERE lower(username) LIKE '%' || lower($1) || '%'
LIMIT $2
OFFSET $3
`

type SearchAccountByUsernameParams struct {
	Lower  string `json:"lower"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) SearchAccountByUsername(ctx context.Context, arg SearchAccountByUsernameParams) ([]Account, error) {
	rows, err := q.db.Query(ctx, searchAccountByUsername, arg.Lower, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TermsAccepted,
			&i.Onboarded,
			&i.Type,
			&i.NationalID,
			&i.Username,
			&i.AvatarUrl,
			&i.Bio,
			&i.VibePoints,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountDetails = `-- name: UpdateAccountDetails :exec
UPDATE accounts
  SET
    username = COALESCE(NULLIF($2::varchar,''), username),
    email = COALESCE(NULLIF($3::varchar, ''), email),
    name = COALESCE(NULLIF($4::varchar,''), name),
    terms_accepted = COALESCE($5::boolean, terms_accepted),
    onboarded = COALESCE($6::boolean, onboarded),
    national_id = COALESCE(NULLIF($7::varchar,''), national_id),
    avatar_url = COALESCE(NULLIF($8::text,''), avatar_url),
    bio = COALESCE(NULLIF($9::text,''), bio),
    updated_at = NOW()
  WHERE id = $1
`

type UpdateAccountDetailsParams struct {
	ID            uuid.UUID `json:"id"`
	Username      string    `json:"username"`
	Email         string    `json:"email"`
	Name          string    `json:"name"`
	TermsAccepted bool      `json:"terms_accepted"`
	Onboarded     bool      `json:"onboarded"`
	NationalID    string    `json:"national_id"`
	AvatarUrl     string    `json:"avatar_url"`
	Bio           string    `json:"bio"`
}

func (q *Queries) UpdateAccountDetails(ctx context.Context, arg UpdateAccountDetailsParams) error {
	_, err := q.db.Exec(ctx, updateAccountDetails,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.Name,
		arg.TermsAccepted,
		arg.Onboarded,
		arg.NationalID,
		arg.AvatarUrl,
		arg.Bio,
	)
	return err
}

const updateAccountPhoneNumber = `-- name: UpdateAccountPhoneNumber :exec
UPDATE accounts
  SET
    phone = COALESCE(NULLIF($2::varchar,''), phone),
    updated_at = NOW()
  WHERE id = $1
`

type UpdateAccountPhoneNumberParams struct {
	ID    uuid.UUID `json:"id"`
	Phone string    `json:"phone"`
}

// Only updates the primary phone number for an account
func (q *Queries) UpdateAccountPhoneNumber(ctx context.Context, arg UpdateAccountPhoneNumberParams) error {
	_, err := q.db.Exec(ctx, updateAccountPhoneNumber, arg.ID, arg.Phone)
	return err
}
