// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: accounts.sql

package repository

import (
	"context"
)

const getAccountByEmail = `-- name: GetAccountByEmail :many
SELECT id, email, name, created_at, updated_at FROM accounts 
WHERE lower(email) = lower($1)
LIMIT 1
`

func (q *Queries) GetAccountByEmail(ctx context.Context, lower *string) ([]Account, error) {
	rows, err := q.db.Query(ctx, getAccountByEmail, lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, email, name, created_at, updated_at FROM accounts 
WHERE id = $1
LIMIT $1
`

func (q *Queries) GetAccountByID(ctx context.Context, limit int32) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, limit)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllAccounts = `-- name: GetAllAccounts :many
SELECT id, email, name, created_at, updated_at FROM accounts 
LIMIT $1
OFFSET $2
`

type GetAllAccountsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAllAccounts(ctx context.Context, arg GetAllAccountsParams) ([]Account, error) {
	rows, err := q.db.Query(ctx, getAllAccounts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAccountByEmail = `-- name: SearchAccountByEmail :many
SELECT id, email, name, created_at, updated_at FROM accounts 
WHERE lower(email) LIKE '%' || lower($1) || '%'
LIMIT $2
OFFSET $3
`

type SearchAccountByEmailParams struct {
	Lower  *string `json:"lower"`
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
}

func (q *Queries) SearchAccountByEmail(ctx context.Context, arg SearchAccountByEmailParams) ([]Account, error) {
	rows, err := q.db.Query(ctx, searchAccountByEmail, arg.Lower, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAccountByName = `-- name: SearchAccountByName :many
SELECT id, email, name, created_at, updated_at FROM accounts 
WHERE lower(name) LIKE '%' || lower($1) || '%'
LIMIT $2
OFFSET $3
`

type SearchAccountByNameParams struct {
	Lower  *string `json:"lower"`
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
}

func (q *Queries) SearchAccountByName(ctx context.Context, arg SearchAccountByNameParams) ([]Account, error) {
	rows, err := q.db.Query(ctx, searchAccountByName, arg.Lower, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
