// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: charge_attempts.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createChargeAttempt = `-- name: CreateChargeAttempt :one
INSERT INTO charge_attempts (id, order_id, payer_phone_number, amount)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, order_id, status, payer_phone_number, amount, notes, requested_at, resolved_at
`

type CreateChargeAttemptParams struct {
	ID               uuid.UUID `json:"id"`
	OrderID          string    `json:"order_id"`
	PayerPhoneNumber string    `json:"payer_phone_number"`
	Amount           int64     `json:"amount"`
}

func (q *Queries) CreateChargeAttempt(ctx context.Context, arg CreateChargeAttemptParams) (ChargeAttempt, error) {
	row := q.db.QueryRow(ctx, createChargeAttempt,
		arg.ID,
		arg.OrderID,
		arg.PayerPhoneNumber,
		arg.Amount,
	)
	var i ChargeAttempt
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Status,
		&i.PayerPhoneNumber,
		&i.Amount,
		&i.Notes,
		&i.RequestedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getChargeAttempt = `-- name: GetChargeAttempt :one
SELECT id, order_id, status, payer_phone_number, amount, notes, requested_at, resolved_at
FROM charge_attempts
WHERE id = $1
`

func (q *Queries) GetChargeAttempt(ctx context.Context, id uuid.UUID) (ChargeAttempt, error) {
	row := q.db.QueryRow(ctx, getChargeAttempt, id)
	var i ChargeAttempt
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Status,
		&i.PayerPhoneNumber,
		&i.Amount,
		&i.Notes,
		&i.RequestedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getPendingChargeAttemptsByOrder = `-- name: GetPendingChargeAttemptsByOrder :many
SELECT id, order_id, status, payer_phone_number, amount, notes, requested_at, resolved_at
FROM charge_attempts
WHERE order_id = $1
  AND status = 'pending'
ORDER BY requested_at DESC
LIMIT $3
OFFSET $2
`

type GetPendingChargeAttemptsByOrderParams struct {
	OrderID    string `json:"order_id"`
	PageOffset int32  `json:"page_offset"`
	PageSize   int32  `json:"page_size"`
}

func (q *Queries) GetPendingChargeAttemptsByOrder(ctx context.Context, arg GetPendingChargeAttemptsByOrderParams) ([]ChargeAttempt, error) {
	rows, err := q.db.Query(ctx, getPendingChargeAttemptsByOrder, arg.OrderID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChargeAttempt{}
	for rows.Next() {
		var i ChargeAttempt
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Status,
			&i.PayerPhoneNumber,
			&i.Amount,
			&i.Notes,
			&i.RequestedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveChargeAttempt = `-- name: ResolveChargeAttempt :one
UPDATE charge_attempts
SET
    status = $1,
    notes = $2,
    resolved_at = now()
WHERE id = $3
  AND status = 'pending'
RETURNING id, order_id, status, payer_phone_number, amount, notes, requested_at, resolved_at
`

type ResolveChargeAttemptParams struct {
	Status ChargeAttemptStatus `json:"status"`
	Notes  *string             `json:"notes"`
	ID     uuid.UUID           `json:"id"`
}

func (q *Queries) ResolveChargeAttempt(ctx context.Context, arg ResolveChargeAttemptParams) (ChargeAttempt, error) {
	row := q.db.QueryRow(ctx, resolveChargeAttempt, arg.Status, arg.Notes, arg.ID)
	var i ChargeAttempt
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Status,
		&i.PayerPhoneNumber,
		&i.Amount,
		&i.Notes,
		&i.RequestedAt,
		&i.ResolvedAt,
	)
	return i, err
}
