// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: charge_attempts.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createChargeAttempt = `-- name: CreateChargeAttempt :one
INSERT INTO charge_attempts (id, order_id, payer_phone_number, amount)
VALUES ($1, $2, $3, $4)
RETURNING id, order_id, status, payer_phone_number, amount, notes, requested_at, resolved_at
`

type CreateChargeAttemptParams struct {
	ID               uuid.UUID `json:"id"`
	OrderID          string    `json:"order_id"`
	PayerPhoneNumber string    `json:"payer_phone_number"`
	Amount           int64     `json:"amount"`
}

func (q *Queries) CreateChargeAttempt(ctx context.Context, arg CreateChargeAttemptParams) (ChargeAttempt, error) {
	row := q.db.QueryRow(ctx, createChargeAttempt,
		arg.ID,
		arg.OrderID,
		arg.PayerPhoneNumber,
		arg.Amount,
	)
	var i ChargeAttempt
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Status,
		&i.PayerPhoneNumber,
		&i.Amount,
		&i.Notes,
		&i.RequestedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getChargeAttempt = `-- name: GetChargeAttempt :one
select id, order_id, status, payer_phone_number, amount, notes, requested_at, resolved_at
from charge_attempts
where id = $1
`

func (q *Queries) GetChargeAttempt(ctx context.Context, id uuid.UUID) (ChargeAttempt, error) {
	row := q.db.QueryRow(ctx, getChargeAttempt, id)
	var i ChargeAttempt
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Status,
		&i.PayerPhoneNumber,
		&i.Amount,
		&i.Notes,
		&i.RequestedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getPendingChargeAttemptByOrder = `-- name: GetPendingChargeAttemptByOrder :one
select id, order_id, status, payer_phone_number, amount, notes, requested_at, resolved_at
from charge_attempts
where order_id = $1 and status = 'pending'
order by requested_at desc
limit $2
offset $3
`

type GetPendingChargeAttemptByOrderParams struct {
	OrderID string `json:"order_id"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) GetPendingChargeAttemptByOrder(ctx context.Context, arg GetPendingChargeAttemptByOrderParams) (ChargeAttempt, error) {
	row := q.db.QueryRow(ctx, getPendingChargeAttemptByOrder, arg.OrderID, arg.Limit, arg.Offset)
	var i ChargeAttempt
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Status,
		&i.PayerPhoneNumber,
		&i.Amount,
		&i.Notes,
		&i.RequestedAt,
		&i.ResolvedAt,
	)
	return i, err
}
