// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entitlements.sql

package repository

import (
	"context"
	"time"
)

const createEntitlement = `-- name: CreateEntitlement :one
insert into public.entitlements (
    plan_id,
    key,
    value,
    unit,
    description
)
select
    p.id,
    $1,
    $2,
    $3,
    $4
from public.plans p
where p.code = $5
returning
    (select code from public.plans where id = entitlements.plan_id) as plan_code,
    key,
    value,
    unit,
    description,
    created_at,
    updated_at
`

type CreateEntitlementParams struct {
	Key         string          `json:"key"`
	Value       int             `json:"value"`
	Unit        EntitlementUnit `json:"unit"`
	Description *string         `json:"description"`
	PlanCode    string          `json:"plan_code"`
}

type CreateEntitlementRow struct {
	PlanCode    string          `json:"plan_code"`
	Key         string          `json:"key"`
	Value       int             `json:"value"`
	Unit        EntitlementUnit `json:"unit"`
	Description *string         `json:"description"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

// Creates a new entitlement under the plan identified by its public code.
// Resolves plan_id internally so callers never see or supply it.
func (q *Queries) CreateEntitlement(ctx context.Context, arg CreateEntitlementParams) (CreateEntitlementRow, error) {
	row := q.db.QueryRow(ctx, createEntitlement,
		arg.Key,
		arg.Value,
		arg.Unit,
		arg.Description,
		arg.PlanCode,
	)
	var i CreateEntitlementRow
	err := row.Scan(
		&i.PlanCode,
		&i.Key,
		&i.Value,
		&i.Unit,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEntitlement = `-- name: DeleteEntitlement :exec
delete from public.entitlements e
using public.plans p
where p.id = e.plan_id and p.code = $1 and e.key = $2
`

type DeleteEntitlementParams struct {
	Code string `json:"code"`
	Key  string `json:"key"`
}

// Deletes an entitlement identified by plan code and key.
func (q *Queries) DeleteEntitlement(ctx context.Context, arg DeleteEntitlementParams) error {
	_, err := q.db.Exec(ctx, deleteEntitlement, arg.Code, arg.Key)
	return err
}

const deleteEntitlementsByPlanCode = `-- name: DeleteEntitlementsByPlanCode :exec
delete from public.entitlements e
using public.plans p
where p.id = e.plan_id and p.code = $1
`

// Deletes all entitlements for a plan, identified by its public code.
// Useful when replacing a plan's entire entitlement set atomically.
func (q *Queries) DeleteEntitlementsByPlanCode(ctx context.Context, code string) error {
	_, err := q.db.Exec(ctx, deleteEntitlementsByPlanCode, code)
	return err
}

const getEntitlement = `-- name: GetEntitlement :one
select
    p.code as plan_code,
    e.key,
    e.value,
    e.unit,
    e.description,
    e.created_at,
    e.updated_at
from public.entitlements e
join public.plans p on p.id = e.plan_id
where p.code = $1 and e.key = $2
`

type GetEntitlementParams struct {
	Code string `json:"code"`
	Key  string `json:"key"`
}

type GetEntitlementRow struct {
	PlanCode    string          `json:"plan_code"`
	Key         string          `json:"key"`
	Value       int             `json:"value"`
	Unit        EntitlementUnit `json:"unit"`
	Description *string         `json:"description"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

// Retrieves a single entitlement by plan code and key.
func (q *Queries) GetEntitlement(ctx context.Context, arg GetEntitlementParams) (GetEntitlementRow, error) {
	row := q.db.QueryRow(ctx, getEntitlement, arg.Code, arg.Key)
	var i GetEntitlementRow
	err := row.Scan(
		&i.PlanCode,
		&i.Key,
		&i.Value,
		&i.Unit,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEntitlementsByPlanCode = `-- name: ListEntitlementsByPlanCode :many
select
    p.code as plan_code,
    e.key,
    e.value,
    e.unit,
    e.description,
    e.created_at,
    e.updated_at
from public.entitlements e
join public.plans p on p.id = e.plan_id
where p.code = $1
order by e.key
`

type ListEntitlementsByPlanCodeRow struct {
	PlanCode    string          `json:"plan_code"`
	Key         string          `json:"key"`
	Value       int             `json:"value"`
	Unit        EntitlementUnit `json:"unit"`
	Description *string         `json:"description"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

// Retrieves all entitlements for a plan, identified by its public code.
func (q *Queries) ListEntitlementsByPlanCode(ctx context.Context, code string) ([]ListEntitlementsByPlanCodeRow, error) {
	rows, err := q.db.Query(ctx, listEntitlementsByPlanCode, code)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEntitlementsByPlanCodeRow{}
	for rows.Next() {
		var i ListEntitlementsByPlanCodeRow
		if err := rows.Scan(
			&i.PlanCode,
			&i.Key,
			&i.Value,
			&i.Unit,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEntitlement = `-- name: UpdateEntitlement :one
update public.entitlements e
set
    value = coalesce($1, e.value),
    unit = coalesce($2, e.unit),
    description = coalesce($3, e.description),
    updated_at = current_timestamp
from public.plans p
where p.id = e.plan_id
  and p.code = $4
  and e.key = $5
returning
    p.code as plan_code,
    e.key,
    e.value,
    e.unit,
    e.description,
    e.created_at,
    e.updated_at
`

type UpdateEntitlementParams struct {
	Value       *int             `json:"value"`
	Unit        *EntitlementUnit `json:"unit"`
	Description *string          `json:"description"`
	PlanCode    string           `json:"plan_code"`
	Key         string           `json:"key"`
}

type UpdateEntitlementRow struct {
	PlanCode    string          `json:"plan_code"`
	Key         string          `json:"key"`
	Value       int             `json:"value"`
	Unit        EntitlementUnit `json:"unit"`
	Description *string         `json:"description"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

// Updates an entitlement identified by plan code and key.
// Only non-null arguments overwrite existing values.
func (q *Queries) UpdateEntitlement(ctx context.Context, arg UpdateEntitlementParams) (UpdateEntitlementRow, error) {
	row := q.db.QueryRow(ctx, updateEntitlement,
		arg.Value,
		arg.Unit,
		arg.Description,
		arg.PlanCode,
		arg.Key,
	)
	var i UpdateEntitlementRow
	err := row.Scan(
		&i.PlanCode,
		&i.Key,
		&i.Value,
		&i.Unit,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
