// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: institution.sql

package repository

import (
	"context"
)

const createInstitution = `-- name: CreateInstitution :one
INSERT INTO institutions (
    name, web_pages, domains, alpha_two_code, country, state_province
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING institution_id, name, web_pages, domains, alpha_two_code, country, state_province
`

type CreateInstitutionParams struct {
	Name          string   `json:"name"`
	WebPages      []string `json:"web_pages"`
	Domains       []string `json:"domains"`
	AlphaTwoCode  *string  `json:"alpha_two_code"`
	Country       *string  `json:"country"`
	StateProvince *string  `json:"state_province"`
}

func (q *Queries) CreateInstitution(ctx context.Context, arg CreateInstitutionParams) (Institution, error) {
	row := q.db.QueryRow(ctx, createInstitution,
		arg.Name,
		arg.WebPages,
		arg.Domains,
		arg.AlphaTwoCode,
		arg.Country,
		arg.StateProvince,
	)
	var i Institution
	err := row.Scan(
		&i.InstitutionID,
		&i.Name,
		&i.WebPages,
		&i.Domains,
		&i.AlphaTwoCode,
		&i.Country,
		&i.StateProvince,
	)
	return i, err
}

const deleteInstitution = `-- name: DeleteInstitution :exec
DELETE FROM institutions
WHERE institution_id = $1
`

func (q *Queries) DeleteInstitution(ctx context.Context, institutionID int32) error {
	_, err := q.db.Exec(ctx, deleteInstitution, institutionID)
	return err
}

const getInstitution = `-- name: GetInstitution :one
SELECT institution_id, name, web_pages, domains, alpha_two_code, country, state_province FROM institutions
WHERE institution_id = $1 LIMIT 1
`

func (q *Queries) GetInstitution(ctx context.Context, institutionID int32) (Institution, error) {
	row := q.db.QueryRow(ctx, getInstitution, institutionID)
	var i Institution
	err := row.Scan(
		&i.InstitutionID,
		&i.Name,
		&i.WebPages,
		&i.Domains,
		&i.AlphaTwoCode,
		&i.Country,
		&i.StateProvince,
	)
	return i, err
}

const listInstitutions = `-- name: ListInstitutions :many
SELECT institution_id, name, web_pages, domains, alpha_two_code, country, state_province FROM institutions
ORDER BY institution_id LIMIT $1 OFFSET $2
`

type ListInstitutionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListInstitutions(ctx context.Context, arg ListInstitutionsParams) ([]Institution, error) {
	rows, err := q.db.Query(ctx, listInstitutions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Institution{}
	for rows.Next() {
		var i Institution
		if err := rows.Scan(
			&i.InstitutionID,
			&i.Name,
			&i.WebPages,
			&i.Domains,
			&i.AlphaTwoCode,
			&i.Country,
			&i.StateProvince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchInstitutionsByName = `-- name: SearchInstitutionsByName :many
SELECT institution_id, name, web_pages, domains, alpha_two_code, country, state_province
FROM institutions
WHERE lower(name) LIKE '%' || lower($3::varchar) || '%'
ORDER BY name
LIMIT $1 OFFSET $2
`

type SearchInstitutionsByNameParams struct {
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
	Name   string `json:"name"`
}

func (q *Queries) SearchInstitutionsByName(ctx context.Context, arg SearchInstitutionsByNameParams) ([]Institution, error) {
	rows, err := q.db.Query(ctx, searchInstitutionsByName, arg.Limit, arg.Offset, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Institution{}
	for rows.Next() {
		var i Institution
		if err := rows.Scan(
			&i.InstitutionID,
			&i.Name,
			&i.WebPages,
			&i.Domains,
			&i.AlphaTwoCode,
			&i.Country,
			&i.StateProvince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInstitution = `-- name: UpdateInstitution :one
UPDATE institutions
SET 
    name = COALESCE(NULLIF($1::varchar, ''), name),
    web_pages = COALESCE(NULLIF($2::text[], '{}'), web_pages),
    domains = COALESCE(NULLIF($3::text[], '{}'), domains),
    alpha_two_code = COALESCE(NULLIF($4::char(2), ''), alpha_two_code),
    country = COALESCE(NULLIF($5::varchar, ''), country),
    state_province = COALESCE(NULLIF($6::varchar, ''), state_province)
WHERE institution_id = $7
RETURNING institution_id, name, web_pages, domains, alpha_two_code, country, state_province
`

type UpdateInstitutionParams struct {
	Name          string   `json:"name"`
	WebPages      []string `json:"web_pages"`
	Domains       []string `json:"domains"`
	AlphaTwoCode  string   `json:"alpha_two_code"`
	Country       string   `json:"country"`
	StateProvince string   `json:"state_province"`
	InstitutionID int32    `json:"institution_id"`
}

func (q *Queries) UpdateInstitution(ctx context.Context, arg UpdateInstitutionParams) (Institution, error) {
	row := q.db.QueryRow(ctx, updateInstitution,
		arg.Name,
		arg.WebPages,
		arg.Domains,
		arg.AlphaTwoCode,
		arg.Country,
		arg.StateProvince,
		arg.InstitutionID,
	)
	var i Institution
	err := row.Scan(
		&i.InstitutionID,
		&i.Name,
		&i.WebPages,
		&i.Domains,
		&i.AlphaTwoCode,
		&i.Country,
		&i.StateProvince,
	)
	return i, err
}
