// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: leaderboard.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const getGlobalLeaderBoardCount = `-- name: GetGlobalLeaderBoardCount :one
SELECT COUNT(*) FROM account_vibepoint_rank
`

func (q *Queries) GetGlobalLeaderBoardCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getGlobalLeaderBoardCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getLeaderBoardRankForUser = `-- name: GetLeaderBoardRankForUser :one
SELECT id, email, name, username, vibe_points, avatar_url, created_at, updated_at, vibe_rank FROM account_vibepoint_rank
WHERE id = $1
LIMIT 1 OFFSET 0
`

// Get the rank for a certain user
func (q *Queries) GetLeaderBoardRankForUser(ctx context.Context, id uuid.UUID) (AccountVibepointRank, error) {
	row := q.db.QueryRow(ctx, getLeaderBoardRankForUser, id)
	var i AccountVibepointRank
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Username,
		&i.VibePoints,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VibeRank,
	)
	return i, err
}

const getLeaderboard = `-- name: GetLeaderboard :many
SELECT id, email, name, username, vibe_points, avatar_url, created_at, updated_at, vibe_rank FROM account_vibepoint_rank
LIMIT $1 OFFSET $2
`

type GetLeaderboardParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Get top N users ranked by vibe points
func (q *Queries) GetLeaderboard(ctx context.Context, arg GetLeaderboardParams) ([]AccountVibepointRank, error) {
	rows, err := q.db.Query(ctx, getLeaderboard, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountVibepointRank{}
	for rows.Next() {
		var i AccountVibepointRank
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Username,
			&i.VibePoints,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VibeRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
