// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: leaderboard.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const getGlobalLeaderBoardCount = `-- name: GetGlobalLeaderBoardCount :one
SELECT COUNT(*) FROM account_vibepoint_rank
`

func (q *Queries) GetGlobalLeaderBoardCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getGlobalLeaderBoardCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getLeaderboard = `-- name: GetLeaderboard :many
SELECT id, email, name, username, vibe_points, avatar_url, created_at, updated_at, vibe_rank FROM account_vibepoint_rank
LIMIT $1 OFFSET $2
`

type GetLeaderboardParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Get top N users ranked by vibe points
func (q *Queries) GetLeaderboard(ctx context.Context, arg GetLeaderboardParams) ([]AccountVibepointRank, error) {
	rows, err := q.db.Query(ctx, getLeaderboard, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountVibepointRank{}
	for rows.Next() {
		var i AccountVibepointRank
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Username,
			&i.VibePoints,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VibeRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLeaderboardAroundUser = `-- name: GetLeaderboardAroundUser :many



SELECT id, email, name, username, vibe_points, avatar_url, created_at, updated_at, vibe_rank FROM account_vibepoint_rank
WHERE id = $1
LIMIT 1 OFFSET 0
`

// Get leaderboard entries around a specific user (user + N above + N below)
// WITH ranked_accounts AS (
//
//	SELECT
//	    id,
//	    email,
//	    name,
//	    username,
//	    avatar_url,
//	    bio,
//	    vibe_points,
//	    created_at,
//	    RANK() OVER (ORDER BY vibe_points DESC, created_at ASC) as rank
//	FROM accounts
//
// ),
// user_rank AS (
//
//	SELECT rank
//	FROM ranked_accounts
//	WHERE id = $1
//
// )
// SELECT
//
//	ra.id,
//	ra.email,
//	ra.name,
//	ra.username,
//	ra.avatar_url,
//	ra.bio,
//	ra.vibe_points,
//	ra.created_at,
//	ra.rank::bigint as rank
//
// FROM ranked_accounts ra
// CROSS JOIN user_rank ur
// WHERE ra.rank BETWEEN (ur.rank - $2) AND (ur.rank + $2)
// ORDER BY ra.rank ASC;
// Get the rank for a certain user
func (q *Queries) GetLeaderboardAroundUser(ctx context.Context, id uuid.UUID) ([]AccountVibepointRank, error) {
	rows, err := q.db.Query(ctx, getLeaderboardAroundUser, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountVibepointRank{}
	for rows.Next() {
		var i AccountVibepointRank
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Username,
			&i.VibePoints,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VibeRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
