// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leaderboard.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getGlobalLeaderBoardCount = `-- name: GetGlobalLeaderBoardCount :one
SELECT COUNT(*) FROM account_vibepoint_rank
`

func (q *Queries) GetGlobalLeaderBoardCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getGlobalLeaderBoardCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getLeaderBoardRankForUser = `-- name: GetLeaderBoardRankForUser :one
SELECT id, email, name, username, vibe_points, avatar_url, created_at, updated_at, vibe_rank FROM account_vibepoint_rank
WHERE id = $1
LIMIT 1 OFFSET 0
`

// Get the rank for a certain user
func (q *Queries) GetLeaderBoardRankForUser(ctx context.Context, id uuid.UUID) (AccountVibepointRank, error) {
	row := q.db.QueryRow(ctx, getLeaderBoardRankForUser, id)
	var i AccountVibepointRank
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Username,
		&i.VibePoints,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VibeRank,
	)
	return i, err
}

const getLeaderboard = `-- name: GetLeaderboard :many
SELECT id, email, name, username, vibe_points, avatar_url, created_at, updated_at, vibe_rank FROM account_vibepoint_rank
ORDER BY vibe_points DESC, id ASC
LIMIT $1 OFFSET $2
`

type GetLeaderboardParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Get top N users ranked by vibe points
func (q *Queries) GetLeaderboard(ctx context.Context, arg GetLeaderboardParams) ([]AccountVibepointRank, error) {
	rows, err := q.db.Query(ctx, getLeaderboard, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountVibepointRank{}
	for rows.Next() {
		var i AccountVibepointRank
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Username,
			&i.VibePoints,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VibeRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLeaderboardAroundUser = `-- name: GetLeaderboardAroundUser :many
WITH ranked AS (
  SELECT
    id,
    email,
    name,
    username,
    vibe_points,
    avatar_url,
    created_at,
    updated_at,
    vibe_rank,
    ROW_NUMBER() OVER (ORDER BY vibe_points DESC, id ASC) AS position,
    COUNT(*) OVER () AS total_users
  FROM account_vibepoint_rank
), target AS (
  SELECT position, total_users
  FROM ranked
  WHERE id = $2::uuid
), window_start AS (
  SELECT LEAST(
    GREATEST(target.position - (($1::bigint - 1) / 2), 1),
    GREATEST(target.total_users - $1::bigint + 1, 1)
  ) AS position
  FROM target
)
SELECT ranked.id, ranked.email, ranked.name, ranked.username, ranked.vibe_points, ranked.avatar_url, ranked.created_at, ranked.updated_at, ranked.vibe_rank, ranked.position, ranked.total_users
FROM ranked, window_start
WHERE ranked.position BETWEEN window_start.position
  AND window_start.position + $1::bigint - 1
ORDER BY ranked.position
`

type GetLeaderboardAroundUserParams struct {
	WindowSize int64     `json:"window_size"`
	UserID     uuid.UUID `json:"user_id"`
}

type GetLeaderboardAroundUserRow struct {
	ID         uuid.UUID  `json:"id"`
	Email      string     `json:"email"`
	Name       string     `json:"name"`
	Username   *string    `json:"username"`
	VibePoints int64      `json:"vibe_points"`
	AvatarUrl  *string    `json:"avatar_url"`
	CreatedAt  *time.Time `json:"created_at"`
	UpdatedAt  *time.Time `json:"updated_at"`
	VibeRank   int64      `json:"vibe_rank"`
	Position   int64      `json:"position"`
	TotalUsers int64      `json:"total_users"`
}

// Returns a stable, centered leaderboard window around one human account.
func (q *Queries) GetLeaderboardAroundUser(ctx context.Context, arg GetLeaderboardAroundUserParams) ([]GetLeaderboardAroundUserRow, error) {
	rows, err := q.db.Query(ctx, getLeaderboardAroundUser, arg.WindowSize, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLeaderboardAroundUserRow{}
	for rows.Next() {
		var i GetLeaderboardAroundUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Username,
			&i.VibePoints,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VibeRank,
			&i.Position,
			&i.TotalUsers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
