// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth_grants.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countOAuthGrantsWithPlaintext = `-- name: CountOAuthGrantsWithPlaintext :one
SELECT count(*) FROM oauth_grants
WHERE access_token_plain IS NOT NULL OR refresh_token_plain IS NOT NULL
`

// Operational check gating the removal of the transitional plaintext columns.
func (q *Queries) CountOAuthGrantsWithPlaintext(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOAuthGrantsWithPlaintext)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getOAuthGrant = `-- name: GetOAuthGrant :one
SELECT id, account_id, provider, external_user_id, access_token_enc, refresh_token_enc, enc_key_version, access_token_plain, refresh_token_plain, granted_scopes, scopes_verified_at, expires_at, last_refreshed_at, refresh_failure_count, last_refresh_error, revoked_at, revoked_reason, created_at, updated_at FROM oauth_grants
WHERE account_id = $1 AND provider = lower($2)
LIMIT 1
`

type GetOAuthGrantParams struct {
	AccountID uuid.UUID `json:"account_id"`
	Lower     string    `json:"lower"`
}

// Retrieves an account's grant for a single provider.
func (q *Queries) GetOAuthGrant(ctx context.Context, arg GetOAuthGrantParams) (OauthGrant, error) {
	row := q.db.QueryRow(ctx, getOAuthGrant, arg.AccountID, arg.Lower)
	var i OauthGrant
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Provider,
		&i.ExternalUserID,
		&i.AccessTokenEnc,
		&i.RefreshTokenEnc,
		&i.EncKeyVersion,
		&i.AccessTokenPlain,
		&i.RefreshTokenPlain,
		&i.GrantedScopes,
		&i.ScopesVerifiedAt,
		&i.ExpiresAt,
		&i.LastRefreshedAt,
		&i.RefreshFailureCount,
		&i.LastRefreshError,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOAuthGrantByID = `-- name: GetOAuthGrantByID :one
SELECT id, account_id, provider, external_user_id, access_token_enc, refresh_token_enc, enc_key_version, access_token_plain, refresh_token_plain, granted_scopes, scopes_verified_at, expires_at, last_refreshed_at, refresh_failure_count, last_refresh_error, revoked_at, revoked_reason, created_at, updated_at FROM oauth_grants WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOAuthGrantByID(ctx context.Context, id uuid.UUID) (OauthGrant, error) {
	row := q.db.QueryRow(ctx, getOAuthGrantByID, id)
	var i OauthGrant
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Provider,
		&i.ExternalUserID,
		&i.AccessTokenEnc,
		&i.RefreshTokenEnc,
		&i.EncKeyVersion,
		&i.AccessTokenPlain,
		&i.RefreshTokenPlain,
		&i.GrantedScopes,
		&i.ScopesVerifiedAt,
		&i.ExpiresAt,
		&i.LastRefreshedAt,
		&i.RefreshFailureCount,
		&i.LastRefreshError,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOAuthGrantsByAccount = `-- name: ListOAuthGrantsByAccount :many
SELECT id, account_id, provider, external_user_id, access_token_enc, refresh_token_enc, enc_key_version, access_token_plain, refresh_token_plain, granted_scopes, scopes_verified_at, expires_at, last_refreshed_at, refresh_failure_count, last_refresh_error, revoked_at, revoked_reason, created_at, updated_at FROM oauth_grants
WHERE account_id = $1
ORDER BY provider
`

// Every provider an account has connected. Not paginated — the provider set
// is small and bounded by the registry.
func (q *Queries) ListOAuthGrantsByAccount(ctx context.Context, accountID uuid.UUID) ([]OauthGrant, error) {
	rows, err := q.db.Query(ctx, listOAuthGrantsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OauthGrant{}
	for rows.Next() {
		var i OauthGrant
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Provider,
			&i.ExternalUserID,
			&i.AccessTokenEnc,
			&i.RefreshTokenEnc,
			&i.EncKeyVersion,
			&i.AccessTokenPlain,
			&i.RefreshTokenPlain,
			&i.GrantedScopes,
			&i.ScopesVerifiedAt,
			&i.ExpiresAt,
			&i.LastRefreshedAt,
			&i.RefreshFailureCount,
			&i.LastRefreshError,
			&i.RevokedAt,
			&i.RevokedReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnverifiedOAuthGrants = `-- name: ListUnverifiedOAuthGrants :many
SELECT id, account_id, provider, external_user_id, access_token_enc, refresh_token_enc, enc_key_version, access_token_plain, refresh_token_plain, granted_scopes, scopes_verified_at, expires_at, last_refreshed_at, refresh_failure_count, last_refresh_error, revoked_at, revoked_reason, created_at, updated_at FROM oauth_grants
WHERE scopes_verified_at IS NULL
  AND revoked_at IS NULL
  AND (refresh_token_enc IS NOT NULL OR refresh_token_plain IS NOT NULL)
ORDER BY updated_at
LIMIT $1
`

// Grants whose scope list is still presumed rather than provider-confirmed.
// Drives the reconciliation worker, which drains the long tail of accounts
// nobody has brokered a token for.
func (q *Queries) ListUnverifiedOAuthGrants(ctx context.Context, limit int32) ([]OauthGrant, error) {
	rows, err := q.db.Query(ctx, listUnverifiedOAuthGrants, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OauthGrant{}
	for rows.Next() {
		var i OauthGrant
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Provider,
			&i.ExternalUserID,
			&i.AccessTokenEnc,
			&i.RefreshTokenEnc,
			&i.EncKeyVersion,
			&i.AccessTokenPlain,
			&i.RefreshTokenPlain,
			&i.GrantedScopes,
			&i.ScopesVerifiedAt,
			&i.ExpiresAt,
			&i.LastRefreshedAt,
			&i.RefreshFailureCount,
			&i.LastRefreshError,
			&i.RevokedAt,
			&i.RevokedReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOAuthGrantRevoked = `-- name: MarkOAuthGrantRevoked :exec
UPDATE oauth_grants
SET revoked_at = NOW(),
    revoked_reason = $1,
    access_token_enc = NULL,
    refresh_token_enc = NULL,
    access_token_plain = NULL,
    refresh_token_plain = NULL,
    expires_at = NULL,
    updated_at = NOW()
WHERE id = $2
`

type MarkOAuthGrantRevokedParams struct {
	Reason *string   `json:"reason"`
	ID     uuid.UUID `json:"id"`
}

// Marks a grant unusable and destroys the stored credentials.
//
// Only for terminal conditions — the provider rejecting the refresh token, or
// an explicit user disconnect. A transient provider failure must use
// RecordOAuthGrantRefreshFailure instead; revoking on a provider outage would
// disconnect every user at once.
func (q *Queries) MarkOAuthGrantRevoked(ctx context.Context, arg MarkOAuthGrantRevokedParams) error {
	_, err := q.db.Exec(ctx, markOAuthGrantRevoked, arg.Reason, arg.ID)
	return err
}

const recordOAuthGrantRefreshFailure = `-- name: RecordOAuthGrantRefreshFailure :exec
UPDATE oauth_grants
SET refresh_failure_count = refresh_failure_count + 1,
    last_refresh_error = $1,
    updated_at = NOW()
WHERE id = $2
`

type RecordOAuthGrantRefreshFailureParams struct {
	LastRefreshError *string   `json:"last_refresh_error"`
	ID               uuid.UUID `json:"id"`
}

// Records a transient refresh failure without touching the credentials.
func (q *Queries) RecordOAuthGrantRefreshFailure(ctx context.Context, arg RecordOAuthGrantRefreshFailureParams) error {
	_, err := q.db.Exec(ctx, recordOAuthGrantRefreshFailure, arg.LastRefreshError, arg.ID)
	return err
}

const upsertOAuthGrant = `-- name: UpsertOAuthGrant :one
INSERT INTO oauth_grants (
    account_id,
    provider,
    external_user_id,
    access_token_enc,
    refresh_token_enc,
    enc_key_version,
    granted_scopes,
    scopes_verified_at,
    expires_at,
    last_refreshed_at,
    access_token_plain,
    refresh_token_plain,
    refresh_failure_count,
    last_refresh_error,
    revoked_at,
    revoked_reason
)
VALUES (
    $1,
    lower($2),
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    NULL,
    NULL,
    0,
    NULL,
    NULL,
    NULL
)
ON CONFLICT (account_id, provider) DO UPDATE SET
    external_user_id  = COALESCE(EXCLUDED.external_user_id, oauth_grants.external_user_id),
    access_token_enc  = EXCLUDED.access_token_enc,
    refresh_token_enc = EXCLUDED.refresh_token_enc,
    enc_key_version   = EXCLUDED.enc_key_version,
    granted_scopes    = EXCLUDED.granted_scopes,
    -- Never let a verified grant fall back to presumed.
    scopes_verified_at = COALESCE(EXCLUDED.scopes_verified_at, oauth_grants.scopes_verified_at),
    expires_at         = EXCLUDED.expires_at,
    last_refreshed_at  = EXCLUDED.last_refreshed_at,
    access_token_plain  = NULL,
    refresh_token_plain = NULL,
    -- A successful write clears the failure state and un-revokes: the account
    -- has just proven it holds working credentials again.
    refresh_failure_count = 0,
    last_refresh_error    = NULL,
    revoked_at            = NULL,
    revoked_reason        = NULL,
    updated_at            = NOW()
RETURNING id, account_id, provider, external_user_id, access_token_enc, refresh_token_enc, enc_key_version, access_token_plain, refresh_token_plain, granted_scopes, scopes_verified_at, expires_at, last_refreshed_at, refresh_failure_count, last_refresh_error, revoked_at, revoked_reason, created_at, updated_at
`

type UpsertOAuthGrantParams struct {
	AccountID        uuid.UUID  `json:"account_id"`
	Provider         string     `json:"provider"`
	ExternalUserID   *string    `json:"external_user_id"`
	AccessTokenEnc   []byte     `json:"access_token_enc"`
	RefreshTokenEnc  []byte     `json:"refresh_token_enc"`
	EncKeyVersion    int16      `json:"enc_key_version"`
	GrantedScopes    []string   `json:"granted_scopes"`
	ScopesVerifiedAt *time.Time `json:"scopes_verified_at"`
	ExpiresAt        *time.Time `json:"expires_at"`
	LastRefreshedAt  *time.Time `json:"last_refreshed_at"`
}

// Records or replaces an account's grant for a provider.
//
// IMPORTANT INVARIANT: both token columns are sealed under the single
// enc_key_version stored on the row, so the caller must always supply BOTH
// ciphertexts, freshly sealed under the active key. When a provider declines
// to rotate the refresh token, the caller re-seals the one it already had
// rather than passing NULL.
//
// Preserving one column while overwriting the other (the obvious
// COALESCE(EXCLUDED.x, oauth_grants.x) shape) would leave ciphertext from an
// old key alongside a bumped enc_key_version and permanently corrupt
// decryption for that row.
//
// The plaintext columns are always cleared, which is what lazily migrates
// backfilled rows off the transitional plaintext as they are used.
func (q *Queries) UpsertOAuthGrant(ctx context.Context, arg UpsertOAuthGrantParams) (OauthGrant, error) {
	row := q.db.QueryRow(ctx, upsertOAuthGrant,
		arg.AccountID,
		arg.Provider,
		arg.ExternalUserID,
		arg.AccessTokenEnc,
		arg.RefreshTokenEnc,
		arg.EncKeyVersion,
		arg.GrantedScopes,
		arg.ScopesVerifiedAt,
		arg.ExpiresAt,
		arg.LastRefreshedAt,
	)
	var i OauthGrant
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Provider,
		&i.ExternalUserID,
		&i.AccessTokenEnc,
		&i.RefreshTokenEnc,
		&i.EncKeyVersion,
		&i.AccessTokenPlain,
		&i.RefreshTokenPlain,
		&i.GrantedScopes,
		&i.ScopesVerifiedAt,
		&i.ExpiresAt,
		&i.LastRefreshedAt,
		&i.RefreshFailureCount,
		&i.LastRefreshError,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
