// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cancelOrder = `-- name: CancelOrder :one
UPDATE public.orders
SET
    status = 'cancelled'::public.order_status,
    cancelled_at = COALESCE(cancelled_at, now()),
    updated_at = now()
WHERE id = $1
  AND status NOT IN (
      'paid'::public.order_status,
      'cancelled'::public.order_status
  )
RETURNING id, user_id, status, subtotal, total, currency, metadata, created_at, updated_at, paid_at, cancelled_at, expires_at, discount, tax
`

// Cancel an order and record the cancellation time.
func (q *Queries) CancelOrder(ctx context.Context, id string) (Order, error) {
	row := q.db.QueryRow(ctx, cancelOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Subtotal,
		&i.Total,
		&i.Currency,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
		&i.CancelledAt,
		&i.ExpiresAt,
		&i.Discount,
		&i.Tax,
	)
	return i, err
}

const countOrdersByUser = `-- name: CountOrdersByUser :one
select count(*)::bigint
from public.orders
where user_id = $1
`

// Count all orders belonging to a user.
func (q *Queries) CountOrdersByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOrdersByUser, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countOrdersByUserAndStatus = `-- name: CountOrdersByUserAndStatus :one
select count(*)::bigint
from public.orders
where user_id = $1 and status = $2
`

type CountOrdersByUserAndStatusParams struct {
	UserID uuid.UUID   `json:"user_id"`
	Status OrderStatus `json:"status"`
}

// Count orders with a specific status for a user.
func (q *Queries) CountOrdersByUserAndStatus(ctx context.Context, arg CountOrdersByUserAndStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOrdersByUserAndStatus, arg.UserID, arg.Status)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO public.orders (
    user_id,
    currency,
    metadata,
    expires_at
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, user_id, status, subtotal, total, currency, metadata, created_at, updated_at, paid_at, cancelled_at, expires_at, discount, tax
`

type CreateOrderParams struct {
	UserID    uuid.UUID  `json:"user_id"`
	Currency  string     `json:"currency"`
	Metadata  []byte     `json:"metadata"`
	ExpiresAt *time.Time `json:"expires_at"`
}

// Create a new empty order and return the created record.
func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.UserID,
		arg.Currency,
		arg.Metadata,
		arg.ExpiresAt,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Subtotal,
		&i.Total,
		&i.Currency,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
		&i.CancelledAt,
		&i.ExpiresAt,
		&i.Discount,
		&i.Tax,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
select id, user_id, status, subtotal, total, currency, metadata, created_at, updated_at, paid_at, cancelled_at, expires_at, discount, tax
from public.orders
where id = $1
`

// Retrieve one order by its order ID.
func (q *Queries) GetOrder(ctx context.Context, id string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Subtotal,
		&i.Total,
		&i.Currency,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
		&i.CancelledAt,
		&i.ExpiresAt,
		&i.Discount,
		&i.Tax,
	)
	return i, err
}

const getUserOrder = `-- name: GetUserOrder :one
select id, user_id, status, subtotal, total, currency, metadata, created_at, updated_at, paid_at, cancelled_at, expires_at, discount, tax
from public.orders
where id = $1 and user_id = $2
`

type GetUserOrderParams struct {
	ID     string    `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// Retrieve one order by ID, limited to the specified user.
func (q *Queries) GetUserOrder(ctx context.Context, arg GetUserOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, getUserOrder, arg.ID, arg.UserID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Subtotal,
		&i.Total,
		&i.Currency,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
		&i.CancelledAt,
		&i.ExpiresAt,
		&i.Discount,
		&i.Tax,
	)
	return i, err
}

const listOrders = `-- name: ListOrders :many
select id, user_id, status, subtotal, total, currency, metadata, created_at, updated_at, paid_at, cancelled_at, expires_at, discount, tax
from public.orders
order by created_at desc
limit $2
offset $1
`

type ListOrdersParams struct {
	PageOffset int32 `json:"page_offset"`
	PageSize   int32 `json:"page_size"`
}

// List all orders with pagination.
func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrders, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.Subtotal,
			&i.Total,
			&i.Currency,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PaidAt,
			&i.CancelledAt,
			&i.ExpiresAt,
			&i.Discount,
			&i.Tax,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByStatus = `-- name: ListOrdersByStatus :many
select id, user_id, status, subtotal, total, currency, metadata, created_at, updated_at, paid_at, cancelled_at, expires_at, discount, tax
from public.orders
where status = $1
order by created_at desc
limit $3
offset $2
`

type ListOrdersByStatusParams struct {
	Status     OrderStatus `json:"status"`
	PageOffset int32       `json:"page_offset"`
	PageSize   int32       `json:"page_size"`
}

// List orders with a specific status.
func (q *Queries) ListOrdersByStatus(ctx context.Context, arg ListOrdersByStatusParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByStatus, arg.Status, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.Subtotal,
			&i.Total,
			&i.Currency,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PaidAt,
			&i.CancelledAt,
			&i.ExpiresAt,
			&i.Discount,
			&i.Tax,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUser = `-- name: ListOrdersByUser :many
select id, user_id, status, subtotal, total, currency, metadata, created_at, updated_at, paid_at, cancelled_at, expires_at, discount, tax
from public.orders
where user_id = $1
order by created_at desc
limit $3
offset $2
`

type ListOrdersByUserParams struct {
	UserID     uuid.UUID `json:"user_id"`
	PageOffset int32     `json:"page_offset"`
	PageSize   int32     `json:"page_size"`
}

// List all orders belonging to a user.
func (q *Queries) ListOrdersByUser(ctx context.Context, arg ListOrdersByUserParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByUser, arg.UserID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.Subtotal,
			&i.Total,
			&i.Currency,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PaidAt,
			&i.CancelledAt,
			&i.ExpiresAt,
			&i.Discount,
			&i.Tax,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOrderPaid = `-- name: MarkOrderPaid :one
UPDATE public.orders
SET
    status = 'paid'::public.order_status,
    paid_at = COALESCE(paid_at, now()),
    updated_at = now()
WHERE id = $1
  AND status NOT IN (
      'paid'::public.order_status,
      'cancelled'::public.order_status
  )
RETURNING id, user_id, status, subtotal, total, currency, metadata, created_at, updated_at, paid_at, cancelled_at, expires_at, discount, tax
`

// Mark an order as paid and record the payment time.
func (q *Queries) MarkOrderPaid(ctx context.Context, id string) (Order, error) {
	row := q.db.QueryRow(ctx, markOrderPaid, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Subtotal,
		&i.Total,
		&i.Currency,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
		&i.CancelledAt,
		&i.ExpiresAt,
		&i.Discount,
		&i.Tax,
	)
	return i, err
}

const recalculateOrderTotals = `-- name: RecalculateOrderTotals :exec
select public.recalculate_order_totals($1)
`

// Recalculate the financial totals for an order from its order items.
func (q *Queries) RecalculateOrderTotals(ctx context.Context, orderID string) error {
	_, err := q.db.Exec(ctx, recalculateOrderTotals, orderID)
	return err
}

const updateOrder = `-- name: UpdateOrder :one
UPDATE public.orders
SET
    currency = $1,
    metadata = $2,
    expires_at = $3,
    updated_at = now()
WHERE id = $4
  AND status NOT IN (
      'paid'::public.order_status,
      'cancelled'::public.order_status
  )
RETURNING id, user_id, status, subtotal, total, currency, metadata, created_at, updated_at, paid_at, cancelled_at, expires_at, discount, tax
`

type UpdateOrderParams struct {
	Currency  string     `json:"currency"`
	Metadata  []byte     `json:"metadata"`
	ExpiresAt *time.Time `json:"expires_at"`
	ID        string     `json:"id"`
}

// Update editable order details without changing financial totals.
func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrder,
		arg.Currency,
		arg.Metadata,
		arg.ExpiresAt,
		arg.ID,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Subtotal,
		&i.Total,
		&i.Currency,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
		&i.CancelledAt,
		&i.ExpiresAt,
		&i.Discount,
		&i.Tax,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE public.orders
SET
    status = $1,
    updated_at = now()
WHERE id = $2
RETURNING id, user_id, status, subtotal, total, currency, metadata, created_at, updated_at, paid_at, cancelled_at, expires_at, discount, tax
`

type UpdateOrderStatusParams struct {
	Status OrderStatus `json:"status"`
	ID     string      `json:"id"`
}

// Update the status of an order and return the updated order.
func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.Status, arg.ID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Subtotal,
		&i.Total,
		&i.Currency,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
		&i.CancelledAt,
		&i.ExpiresAt,
		&i.Discount,
		&i.Tax,
	)
	return i, err
}
