// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order_items.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO public.order_items (
    order_id,
    added_by,
    unit_price,
    discount,
    quantity,
    tax,
    plan_id
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, order_id, added_by, unit_price, discount, quantity, tax, plan_id, created_at, updated_at
`

type CreateOrderItemParams struct {
	OrderID   string    `json:"order_id"`
	AddedBy   uuid.UUID `json:"added_by"`
	UnitPrice int64     `json:"unit_price"`
	Discount  int64     `json:"discount"`
	Quantity  int16     `json:"quantity"`
	Tax       int64     `json:"tax"`
	PlanID    *int32    `json:"plan_id"`
}

// Create a new order item and return the created record.
func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.AddedBy,
		arg.UnitPrice,
		arg.Discount,
		arg.Quantity,
		arg.Tax,
		arg.PlanID,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.AddedBy,
		&i.UnitPrice,
		&i.Discount,
		&i.Quantity,
		&i.Tax,
		&i.PlanID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrderItem = `-- name: DeleteOrderItem :exec
delete from public.order_items
where id = $1
`

// Delete one order item by its ID.
func (q *Queries) DeleteOrderItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrderItem, id)
	return err
}

const deleteOrderItemsByOrder = `-- name: DeleteOrderItemsByOrder :exec
delete from public.order_items
where order_id = $1
`

// Delete all items belonging to an order.
func (q *Queries) DeleteOrderItemsByOrder(ctx context.Context, orderID string) error {
	_, err := q.db.Exec(ctx, deleteOrderItemsByOrder, orderID)
	return err
}

const getOrderItem = `-- name: GetOrderItem :one
select id, order_id, added_by, unit_price, discount, quantity, tax, plan_id, created_at, updated_at
from public.order_items
where id = $1
`

// Retrieve one order item by its ID.
func (q *Queries) GetOrderItem(ctx context.Context, id uuid.UUID) (OrderItem, error) {
	row := q.db.QueryRow(ctx, getOrderItem, id)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.AddedBy,
		&i.UnitPrice,
		&i.Discount,
		&i.Quantity,
		&i.Tax,
		&i.PlanID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrderItemsByOrder = `-- name: ListOrderItemsByOrder :many
select id, order_id, added_by, unit_price, discount, quantity, tax, plan_id, created_at, updated_at
from public.order_items
where order_id = $1
order by created_at asc
`

// Retrieve all items belonging to an order.
func (q *Queries) ListOrderItemsByOrder(ctx context.Context, orderID string) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItemsByOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.AddedBy,
			&i.UnitPrice,
			&i.Discount,
			&i.Quantity,
			&i.Tax,
			&i.PlanID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderItem = `-- name: UpdateOrderItem :one
UPDATE public.order_items
SET
    unit_price = $1,
    discount = $2,
    quantity = $3,
    tax = $4,
    plan_id = $5,
    updated_at = now()
WHERE id = $6
RETURNING id, order_id, added_by, unit_price, discount, quantity, tax, plan_id, created_at, updated_at
`

type UpdateOrderItemParams struct {
	UnitPrice int64     `json:"unit_price"`
	Discount  int64     `json:"discount"`
	Quantity  int16     `json:"quantity"`
	Tax       int64     `json:"tax"`
	PlanID    *int32    `json:"plan_id"`
	ID        uuid.UUID `json:"id"`
}

// Update an existing order item and return the updated record.
func (q *Queries) UpdateOrderItem(ctx context.Context, arg UpdateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, updateOrderItem,
		arg.UnitPrice,
		arg.Discount,
		arg.Quantity,
		arg.Tax,
		arg.PlanID,
		arg.ID,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.AddedBy,
		&i.UnitPrice,
		&i.Discount,
		&i.Quantity,
		&i.Tax,
		&i.PlanID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
