// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plans.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPlan = `-- name: CreatePlan :one
INSERT INTO public.plans (
    code,
    name,
    price,
    currency,
    billing_interval_days,
    active,
    visible,
    created_by,
    description
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING
    code,
    name,
    price,
    currency,
    billing_interval_days,
    active,
    visible,
    description,
    created_by,
    created_at,
    updated_at
`

type CreatePlanParams struct {
	Code                string     `json:"code"`
	Name                string     `json:"name"`
	Price               int64      `json:"price"`
	Currency            string     `json:"currency"`
	BillingIntervalDays int16      `json:"billing_interval_days"`
	Active              *bool      `json:"active"`
	Visible             *bool      `json:"visible"`
	CreatedBy           *uuid.UUID `json:"created_by"`
	Description         *string    `json:"description"`
}

type CreatePlanRow struct {
	Code                string     `json:"code"`
	Name                string     `json:"name"`
	Price               int64      `json:"price"`
	Currency            string     `json:"currency"`
	BillingIntervalDays int16      `json:"billing_interval_days"`
	Active              *bool      `json:"active"`
	Visible             *bool      `json:"visible"`
	Description         *string    `json:"description"`
	CreatedBy           *uuid.UUID `json:"created_by"`
	CreatedAt           *time.Time `json:"created_at"`
	UpdatedAt           *time.Time `json:"updated_at"`
}

// Creates a plan and returns its details.
func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (CreatePlanRow, error) {
	row := q.db.QueryRow(ctx, createPlan,
		arg.Code,
		arg.Name,
		arg.Price,
		arg.Currency,
		arg.BillingIntervalDays,
		arg.Active,
		arg.Visible,
		arg.CreatedBy,
		arg.Description,
	)
	var i CreatePlanRow
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.Price,
		&i.Currency,
		&i.BillingIntervalDays,
		&i.Active,
		&i.Visible,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlanByCode = `-- name: GetPlanByCode :one
select
    code,
    name,
    price,
    currency,
    billing_interval_days,
    active,
    visible,
    description,
    created_by,
    created_at,
    updated_at
from public.plans
where code = $1
`

type GetPlanByCodeRow struct {
	Code                string     `json:"code"`
	Name                string     `json:"name"`
	Price               int64      `json:"price"`
	Currency            string     `json:"currency"`
	BillingIntervalDays int16      `json:"billing_interval_days"`
	Active              *bool      `json:"active"`
	Visible             *bool      `json:"visible"`
	Description         *string    `json:"description"`
	CreatedBy           *uuid.UUID `json:"created_by"`
	CreatedAt           *time.Time `json:"created_at"`
	UpdatedAt           *time.Time `json:"updated_at"`
}

// Retrieves a plan by its code
func (q *Queries) GetPlanByCode(ctx context.Context, code string) (GetPlanByCodeRow, error) {
	row := q.db.QueryRow(ctx, getPlanByCode, code)
	var i GetPlanByCodeRow
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.Price,
		&i.Currency,
		&i.BillingIntervalDays,
		&i.Active,
		&i.Visible,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlans = `-- name: ListPlans :many
select
    code,
    name,
    price,
    currency,
    billing_interval_days,
    active,
    visible,
    description,
    created_by,
    created_at,
    updated_at
from public.plans
where $1::bool is null or visible = $1::bool
`

type ListPlansRow struct {
	Code                string     `json:"code"`
	Name                string     `json:"name"`
	Price               int64      `json:"price"`
	Currency            string     `json:"currency"`
	BillingIntervalDays int16      `json:"billing_interval_days"`
	Active              *bool      `json:"active"`
	Visible             *bool      `json:"visible"`
	Description         *string    `json:"description"`
	CreatedBy           *uuid.UUID `json:"created_by"`
	CreatedAt           *time.Time `json:"created_at"`
	UpdatedAt           *time.Time `json:"updated_at"`
}

// Retrieves plans.
// No pagination logic is inserted as we don't anticipate having many plans
// at the moment.
func (q *Queries) ListPlans(ctx context.Context, visible *bool) ([]ListPlansRow, error) {
	rows, err := q.db.Query(ctx, listPlans, visible)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlansRow{}
	for rows.Next() {
		var i ListPlansRow
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.Price,
			&i.Currency,
			&i.BillingIntervalDays,
			&i.Active,
			&i.Visible,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlan = `-- name: UpdatePlan :one
UPDATE public.plans
SET
    price = COALESCE($1, price),
    currency = COALESCE($2, currency),
    billing_interval_days = COALESCE($3, billing_interval_days),
    active = COALESCE($4, active),
    visible = COALESCE($5, visible),
    description = COALESCE($6, description),
    updated_at = NOW()
WHERE code = $7
RETURNING
    code,
    name,
    price,
    currency,
    billing_interval_days,
    active,
    visible,
    description,
    created_by,
    created_at,
    updated_at
`

type UpdatePlanParams struct {
	Price           *int64  `json:"price"`
	Currency        *string `json:"currency"`
	BillingInterval *int16  `json:"billing_interval"`
	Active          *bool   `json:"active"`
	Visible         *bool   `json:"visible"`
	Description     *string `json:"description"`
	Code            string  `json:"code"`
}

type UpdatePlanRow struct {
	Code                string     `json:"code"`
	Name                string     `json:"name"`
	Price               int64      `json:"price"`
	Currency            string     `json:"currency"`
	BillingIntervalDays int16      `json:"billing_interval_days"`
	Active              *bool      `json:"active"`
	Visible             *bool      `json:"visible"`
	Description         *string    `json:"description"`
	CreatedBy           *uuid.UUID `json:"created_by"`
	CreatedAt           *time.Time `json:"created_at"`
	UpdatedAt           *time.Time `json:"updated_at"`
}

// Updates only the provided fields and returns the updated plan.
func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) (UpdatePlanRow, error) {
	row := q.db.QueryRow(ctx, updatePlan,
		arg.Price,
		arg.Currency,
		arg.BillingInterval,
		arg.Active,
		arg.Visible,
		arg.Description,
		arg.Code,
	)
	var i UpdatePlanRow
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.Price,
		&i.Currency,
		&i.BillingIntervalDays,
		&i.Active,
		&i.Visible,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
