// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddAccountInstitution(ctx context.Context, arg AddAccountInstitutionParams) (AddAccountInstitutionRow, error)
	// Assigns a role to a user
	AssignRole(ctx context.Context, arg AssignRoleParams) (UserRole, error)
	// Assigns a permission to a role
	AssignRolePermission(ctx context.Context, arg AssignRolePermissionParams) (RolePermission, error)
	ClaimRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error)
	CleanupExpiredServiceTokens(ctx context.Context) error
	// Operational check gating the removal of the transitional plaintext columns.
	CountOAuthGrantsWithPlaintext(ctx context.Context) (int64, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	// Creates an activity.
	// An activity is basically an action that a user can
	// take to be awarded vibe points
	CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error)
	// Creates a new entitlement under the plan identified by its public code.
	// Resolves plan_id internally so callers never see or supply it.
	CreateEntitlement(ctx context.Context, arg CreateEntitlementParams) (CreateEntitlementRow, error)
	CreateInstitution(ctx context.Context, arg CreateInstitutionParams) (Institution, error)
	// Creates a permission on the database
	CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error)
	// Creates a plan and returns its details.
	CreatePlan(ctx context.Context, arg CreatePlanParams) (CreatePlanRow, error)
	// Creates a role
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateServiceToken(ctx context.Context, arg CreateServiceTokenParams) (ServiceToken, error)
	CreateSocial(ctx context.Context, arg CreateSocialParams) (Social, error)
	// Creates a streak milestone.
	CreateStreakMilestone(ctx context.Context, arg CreateStreakMilestoneParams) (StreakMilestone, error)
	DeleteActivity(ctx context.Context, id uuid.UUID) error
	// Deletes an entitlement identified by plan code and key.
	DeleteEntitlement(ctx context.Context, arg DeleteEntitlementParams) error
	// Deletes all entitlements for a plan, identified by its public code.
	// Useful when replacing a plan's entire entitlement set atomically.
	DeleteEntitlementsByPlanCode(ctx context.Context, code string) error
	DeleteInstitution(ctx context.Context, institutionID int32) error
	DeleteServiceToken(ctx context.Context, id uuid.UUID) error
	// Deletes streak milestone by ID
	DeleteStreakMilestoneByID(ctx context.Context, id uuid.UUID) error
	GetAccountByEmail(ctx context.Context, email string) (Account, error)
	GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error)
	// Returns a list of all social accounts by provider
	// note that the results are paginated using the limit offset scheme
	GetAccountByProvider(ctx context.Context, arg GetAccountByProviderParams) ([]Social, error)
	GetAccountByUsername(ctx context.Context, username string) (Account, error)
	// Returns the number of all human accounts in the system
	GetAccountsCount(ctx context.Context) (int64, error)
	// Returns an activity specified by its id
	GetActivityByID(ctx context.Context, id uuid.UUID) (Activity, error)
	// Returns a list of oauth providers that they've granted
	// note that the results are not paginated since we dont support a
	// whole lot of social oauth providers
	GetAllAccountSocials(ctx context.Context, accountID uuid.UUID) ([]Social, error)
	// Returns only accounts of the 'human' type
	GetAllAccounts(ctx context.Context, arg GetAllAccountsParams) ([]Account, error)
	// Returns all the active activities in the system paginated using the
	// limit-offset schme
	GetAllActiveActivities(ctx context.Context, arg GetAllActiveActivitiesParams) ([]Activity, error)
	// Returns all the active activities count in the system
	GetAllActiveActivitiesCount(ctx context.Context) (int64, error)
	// Returns all active streak milestones count
	GetAllActiveStreakMilestoneCount(ctx context.Context) (int64, error)
	// Returns all the activities in the system paginated using the
	// limit-offset schme
	GetAllActivities(ctx context.Context, arg GetAllActivitiesParams) ([]Activity, error)
	// Returns all activities count regardless of activity status
	GetAllActivitiesCount(ctx context.Context) (int64, error)
	// Returns all the inactive activities in the system paginated using the
	// limit-offset schme
	GetAllInactiveActivities(ctx context.Context, arg GetAllInactiveActivitiesParams) ([]Activity, error)
	// Returns all the inactive activities count in the system
	GetAllInactiveActivitiesCount(ctx context.Context) (int64, error)
	// Returns all inactive streak milestones count
	GetAllInactiveStreakMilestoneCount(ctx context.Context) (int64, error)
	GetAllPermissions(ctx context.Context, arg GetAllPermissionsParams) ([]Permission, error)
	// Retrieves a list of roles
	GetAllRoles(ctx context.Context, arg GetAllRolesParams) ([]Role, error)
	// Returns all streaks by activity status
	GetAllStreaksMilestoneByActive(ctx context.Context, arg GetAllStreaksMilestoneByActiveParams) ([]StreakMilestone, error)
	// Returns activity a certain user specified by their id has completed ordered
	// from the most recent to the oldest
	GetAllUserActivityCompletions(ctx context.Context, arg GetAllUserActivityCompletionsParams) ([]ActivityCompletion, error)
	// Returns the number of record that have been done on the user's completed
	// activities
	GetAllUserActivityCompletionsCount(ctx context.Context, accountID uuid.UUID) (int64, error)
	// Retrieves only the role name that the user has been granted
	GetAllUserRoleNames(ctx context.Context, userID uuid.UUID) ([]string, error)
	// Retrieves all roles that a user has
	GetAllUserRoles(ctx context.Context, userID uuid.UUID) ([]UserRolesView, error)
	// Retrieves a single entitlement by plan code and key.
	GetEntitlement(ctx context.Context, arg GetEntitlementParams) (GetEntitlementRow, error)
	GetGlobalLeaderBoardCount(ctx context.Context) (int64, error)
	GetInstitution(ctx context.Context, institutionID int32) (Institution, error)
	// Returns the number of all institutions in the system
	GetInstitutionsCount(ctx context.Context) (int64, error)
	// Get the rank for a certain user
	GetLeaderBoardRankForUser(ctx context.Context, id uuid.UUID) (AccountVibepointRank, error)
	// Get top N users ranked by vibe points
	GetLeaderboard(ctx context.Context, arg GetLeaderboardParams) ([]AccountVibepointRank, error)
	// Retrieves an account's grant for a single provider.
	GetOAuthGrant(ctx context.Context, arg GetOAuthGrantParams) (OauthGrant, error)
	GetOAuthGrantByID(ctx context.Context, id uuid.UUID) (OauthGrant, error)
	GetPermissionByID(ctx context.Context, id uuid.UUID) (Permission, error)
	// Retrieves a plan by its code
	GetPlanByCode(ctx context.Context, code string) (GetPlanByCodeRow, error)
	// Retrieves an earlier issued refresh token given its hash
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	// Retrieves a role specified by its id
	GetRoleByID(ctx context.Context, id uuid.UUID) (Role, error)
	GetRoleByName(ctx context.Context, name string) (Role, error)
	// Retrieves all permissions that a re assigned to a role
	GetRolePermissions(ctx context.Context, roleID uuid.UUID) ([]RolePermissionsView, error)
	GetServiceTokenByHash(ctx context.Context, tokenHash string) (ServiceToken, error)
	GetServiceTokenByID(ctx context.Context, id uuid.UUID) (ServiceToken, error)
	GetServiceTokenUsageStats(ctx context.Context, accountID uuid.UUID) (GetServiceTokenUsageStatsRow, error)
	GetSocialByExternalUserID(ctx context.Context, userID string) (Social, error)
	// Retrieves all user devices that a user has ever used to access their accounts
	// Results are orderd by the most recent device used to access the account
	GetUserDevices(ctx context.Context, userID uuid.UUID) ([]UserDevice, error)
	// Returns all permission names that have been granted to a user
	GetUserPermissionNames(ctx context.Context, userID uuid.UUID) ([]string, error)
	// Returns all permissions associated to a user
	GetUserPermissions(ctx context.Context, userID uuid.UUID) ([]UserPermissionsView, error)
	GetUserStreaks(ctx context.Context, accountID uuid.UUID) ([]interface{}, error)
	ListAccountsForInstitution(ctx context.Context, arg ListAccountsForInstitutionParams) ([]Account, error)
	ListActiveServiceTokens(ctx context.Context) ([]ActiveServiceToken, error)
	// Retrieves all entitlements for a plan, identified by its public code.
	ListEntitlementsByPlanCode(ctx context.Context, code string) ([]ListEntitlementsByPlanCodeRow, error)
	ListInstitutionConnections(ctx context.Context, arg ListInstitutionConnectionsParams) ([]AccountInstitution, error)
	ListInstitutions(ctx context.Context, arg ListInstitutionsParams) ([]Institution, error)
	ListInstitutionsForAccount(ctx context.Context, arg ListInstitutionsForAccountParams) ([]Institution, error)
	// Every provider an account has connected. Not paginated — the provider set
	// is small and bounded by the registry.
	ListOAuthGrantsByAccount(ctx context.Context, accountID uuid.UUID) ([]OauthGrant, error)
	// Retrieves plans.
	// No pagination logic is inserted as we don't anticipate having many plans
	// at the moment.
	ListPlans(ctx context.Context, visible *bool) ([]ListPlansRow, error)
	ListServiceTokensByAccount(ctx context.Context, accountID uuid.UUID) ([]ServiceToken, error)
	ListServiceTokensNeedingRotation(ctx context.Context) ([]ServiceToken, error)
	// Grants whose scope list is still presumed rather than provider-confirmed.
	// Drives the reconciliation worker, which drains the long tail of accounts
	// nobody has brokered a token for.
	ListUnverifiedOAuthGrants(ctx context.Context, limit int32) ([]OauthGrant, error)
	// Marks an account for deletion
	MarkAccountForDeletion(ctx context.Context, id uuid.UUID) error
	// Recovers an account from scheduled deletion
	MarkAccountForRecovery(ctx context.Context, id uuid.UUID) error
	// Marks a grant unusable and destroys the stored credentials.
	//
	// Only for terminal conditions — the provider rejecting the refresh token, or
	// an explicit user disconnect. A transient provider failure must use
	// RecordOAuthGrantRefreshFailure instead; revoking on a provider outage would
	// disconnect every user at once.
	MarkOAuthGrantRevoked(ctx context.Context, arg MarkOAuthGrantRevokedParams) error
	// Marks and persists that a refresh token has been used
	MarkRefreshTokenUsed(ctx context.Context, id uuid.UUID) error
	MarkTokensForRotation(ctx context.Context) error
	// SELECT *
	// FROM record_activity_completion(@account_id::uuid, @activity_id::uuid, @metadata::jsonb);
	RecordActivityCompletion(ctx context.Context, arg RecordActivityCompletionParams) (RecordActivityCompletionRow, error)
	// Persists an issued refresh token's information to the db
	RecordIssuedRefreshToken(ctx context.Context, arg RecordIssuedRefreshTokenParams) (RefreshToken, error)
	// Records an issued access token's information to the db
	RecordIssuedToken(ctx context.Context, arg RecordIssuedTokenParams) (IssuedToken, error)
	// Records a transient refresh failure without touching the credentials.
	RecordOAuthGrantRefreshFailure(ctx context.Context, arg RecordOAuthGrantRefreshFailureParams) error
	// Inserts a new device. If the device is already registered (same user + push_token),
	// only last_active_at, ip_address, and country are updated.
	RecordUserDevice(ctx context.Context, arg RecordUserDeviceParams) (UserDevice, error)
	RemoveAccountInstitution(ctx context.Context, arg RemoveAccountInstitutionParams) error
	// RevokeRefreshTokenFamily revokes all active refresh tokens belonging to a given family.
	// This is triggered when a refresh token reuse attack is detected — i.e. a token that
	// has already been used is presented again. Revoking the entire family forces the user
	// to re-authenticate, invalidating any tokens the attacker may have obtained.
	RevokeRefreshTokenFamily(ctx context.Context, familyID uuid.UUID) error
	// Revokes a role from a user
	RevokeRole(ctx context.Context, arg RevokeRoleParams) error
	// Revokes a permission from a role
	RevokeRolePermission(ctx context.Context, arg RevokeRolePermissionParams) error
	RevokeServiceToken(ctx context.Context, id uuid.UUID) error
	RotateServiceToken(ctx context.Context, arg RotateServiceTokenParams) error
	SearchAccountByEmail(ctx context.Context, arg SearchAccountByEmailParams) ([]Account, error)
	SearchAccountByName(ctx context.Context, arg SearchAccountByNameParams) ([]Account, error)
	SearchAccountByUsername(ctx context.Context, arg SearchAccountByUsernameParams) ([]Account, error)
	SearchInstitutionsByName(ctx context.Context, arg SearchInstitutionsByNameParams) ([]Institution, error)
	UpdateAccountDetails(ctx context.Context, arg UpdateAccountDetailsParams) error
	// Only updates the primary phone number for an account
	UpdateAccountPhoneNumber(ctx context.Context, arg UpdateAccountPhoneNumberParams) error
	// Updates an activity specified by its ID
	UpdateActivity(ctx context.Context, arg UpdateActivityParams) (Activity, error)
	// Updates an entitlement identified by plan code and key.
	// Only non-null arguments overwrite existing values.
	UpdateEntitlement(ctx context.Context, arg UpdateEntitlementParams) (UpdateEntitlementRow, error)
	UpdateInstitution(ctx context.Context, arg UpdateInstitutionParams) (Institution, error)
	UpdatePermission(ctx context.Context, arg UpdatePermissionParams) (Permission, error)
	// Updates only the provided fields and returns the updated plan.
	UpdatePlan(ctx context.Context, arg UpdatePlanParams) (UpdatePlanRow, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error)
	UpdateServiceToken(ctx context.Context, arg UpdateServiceTokenParams) error
	UpdateServiceTokenLastUsed(ctx context.Context, id uuid.UUID) error
	UpdateSocial(ctx context.Context, arg UpdateSocialParams) (Social, error)
	// Records or replaces an account's grant for a provider.
	//
	// IMPORTANT INVARIANT: both token columns are sealed under the single
	// enc_key_version stored on the row, so the caller must always supply BOTH
	// ciphertexts, freshly sealed under the active key. When a provider declines
	// to rotate the refresh token, the caller re-seals the one it already had
	// rather than passing NULL.
	//
	// Preserving one column while overwriting the other (the obvious
	// COALESCE(EXCLUDED.x, oauth_grants.x) shape) would leave ciphertext from an
	// old key alongside a bumped enc_key_version and permanently corrupt
	// decryption for that row.
	//
	// The plaintext columns are always cleared, which is what lazily migrates
	// backfilled rows off the transitional plaintext as they are used.
	UpsertOAuthGrant(ctx context.Context, arg UpsertOAuthGrantParams) (OauthGrant, error)
}

var _ Querier = (*Queries)(nil)
