// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: roles.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const assignRole = `-- name: AssignRole :one
INSERT INTO user_roles  (
  user_id, role_id
) VALUES ( $1, $2 )
RETURNING user_id, role_id
`

type AssignRoleParams struct {
	UserID uuid.UUID `json:"user_id"`
	RoleID uuid.UUID `json:"role_id"`
}

// Assigns a role to a user
func (q *Queries) AssignRole(ctx context.Context, arg AssignRoleParams) (UserRole, error) {
	row := q.db.QueryRow(ctx, assignRole, arg.UserID, arg.RoleID)
	var i UserRole
	err := row.Scan(&i.UserID, &i.RoleID)
	return i, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles ( 
  name, description
) VALUES ( $1, $2 )
RETURNING id, name, description, created_at, updated_at, is_default
`

type CreateRoleParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

// Creates a role
func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole, arg.Name, arg.Description)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
	)
	return i, err
}

const getAllRoles = `-- name: GetAllRoles :many
SELECT id, name, description, created_at, updated_at, is_default FROM roles 
LIMIT $1
OFFSET $2
`

type GetAllRolesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Retrieves a list of roles
func (q *Queries) GetAllRoles(ctx context.Context, arg GetAllRolesParams) ([]Role, error) {
	rows, err := q.db.Query(ctx, getAllRoles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUserRoles = `-- name: GetAllUserRoles :many
SELECT user_id, email, name, role_id, role_name, role_description, role_created_at FROM user_roles_view WHERE user_id = $1
`

// Retrieves all roles that a user has
func (q *Queries) GetAllUserRoles(ctx context.Context, userID uuid.UUID) ([]UserRolesView, error) {
	rows, err := q.db.Query(ctx, getAllUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserRolesView{}
	for rows.Next() {
		var i UserRolesView
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.Name,
			&i.RoleID,
			&i.RoleName,
			&i.RoleDescription,
			&i.RoleCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, name, description, created_at, updated_at, is_default FROM roles WHERE id = $1
`

// Retrieves a role specified by its id
func (q *Queries) GetRoleByID(ctx context.Context, id uuid.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
	)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, name, description, created_at, updated_at, is_default FROM roles 
WHERE name = $1
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
	)
	return i, err
}

const getRolePermissions = `-- name: GetRolePermissions :many
SELECT role_id, role_name, role_description, permission_id, permission_name FROM role_permissions_view
WHERE role_id = $1
`

// Retrieves all permissions that a re assigned to a role
func (q *Queries) GetRolePermissions(ctx context.Context, roleID uuid.UUID) ([]RolePermissionsView, error) {
	rows, err := q.db.Query(ctx, getRolePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RolePermissionsView{}
	for rows.Next() {
		var i RolePermissionsView
		if err := rows.Scan(
			&i.RoleID,
			&i.RoleName,
			&i.RoleDescription,
			&i.PermissionID,
			&i.PermissionName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeRole = `-- name: RevokeRole :exec
DELETE FROM user_roles
  WHERE user_id = $1 AND role_id = $2
`

type RevokeRoleParams struct {
	UserID uuid.UUID `json:"user_id"`
	RoleID uuid.UUID `json:"role_id"`
}

// Revokes a role from a user
func (q *Queries) RevokeRole(ctx context.Context, arg RevokeRoleParams) error {
	_, err := q.db.Exec(ctx, revokeRole, arg.UserID, arg.RoleID)
	return err
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles
  SET name =  COALESCE($2, name),
  description = COALESCE($3, description)
  WHERE id = $1
RETURNING id, name, description, created_at, updated_at, is_default
`

type UpdateRoleParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, updateRole, arg.ID, arg.Name, arg.Description)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
	)
	return i, err
}
