// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: streaks.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createStreakMilestone = `-- name: CreateStreakMilestone :one
INSERT INTO streak_milestones (
  activity_id, days_required, bonus_points, title, description, is_active
) VALUES ( $1, $2, $3, $4, $5, $6 )
RETURNING id, activity_id, days_required, bonus_points, title, description, is_active
`

type CreateStreakMilestoneParams struct {
	ActivityID   pgtype.UUID `json:"activity_id"`
	DaysRequired int16       `json:"days_required"`
	BonusPoints  int16       `json:"bonus_points"`
	Title        string      `json:"title"`
	Description  *string     `json:"description"`
	IsActive     *bool       `json:"is_active"`
}

// Creates a streak milestone.
func (q *Queries) CreateStreakMilestone(ctx context.Context, arg CreateStreakMilestoneParams) (StreakMilestone, error) {
	row := q.db.QueryRow(ctx, createStreakMilestone,
		arg.ActivityID,
		arg.DaysRequired,
		arg.BonusPoints,
		arg.Title,
		arg.Description,
		arg.IsActive,
	)
	var i StreakMilestone
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.DaysRequired,
		&i.BonusPoints,
		&i.Title,
		&i.Description,
		&i.IsActive,
	)
	return i, err
}

const deleteStreakMilestoneByID = `-- name: DeleteStreakMilestoneByID :exec
DELETE FROM streak_milestones WHERE id = $1
`

// Deletes streak milestone by ID
func (q *Queries) DeleteStreakMilestoneByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteStreakMilestoneByID, id)
	return err
}

const getAllActiveStreakMilestoneCount = `-- name: GetAllActiveStreakMilestoneCount :one
SELECT count(id) FROM streak_milestones WHERE is_active = true
`

// Returns all active streak milestones count
func (q *Queries) GetAllActiveStreakMilestoneCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getAllActiveStreakMilestoneCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAllInactiveStreakMilestoneCount = `-- name: GetAllInactiveStreakMilestoneCount :one
SELECT count(id) FROM streak_milestones WHERE is_active = false
`

// Returns all inactive streak milestones count
func (q *Queries) GetAllInactiveStreakMilestoneCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getAllInactiveStreakMilestoneCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAllStreaksMilestoneByActive = `-- name: GetAllStreaksMilestoneByActive :many
SELECT id, activity_id, days_required, bonus_points, title, description, is_active FROM streak_milestones WHERE is_active = $1 
LIMIT $2
OFFSET $3
`

type GetAllStreaksMilestoneByActiveParams struct {
	IsActive *bool `json:"is_active"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

// Returns all streaks by activity status
func (q *Queries) GetAllStreaksMilestoneByActive(ctx context.Context, arg GetAllStreaksMilestoneByActiveParams) ([]StreakMilestone, error) {
	rows, err := q.db.Query(ctx, getAllStreaksMilestoneByActive, arg.IsActive, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StreakMilestone{}
	for rows.Next() {
		var i StreakMilestone
		if err := rows.Scan(
			&i.ID,
			&i.ActivityID,
			&i.DaysRequired,
			&i.BonusPoints,
			&i.Title,
			&i.Description,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserStreaks = `-- name: GetUserStreaks :many
SELECT get_user_streaks
FROM get_user_streaks($1::uuid)
`

func (q *Queries) GetUserStreaks(ctx context.Context, accountID uuid.UUID) ([]interface{}, error) {
	rows, err := q.db.Query(ctx, getUserStreaks, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []interface{}{}
	for rows.Next() {
		var get_user_streaks interface{}
		if err := rows.Scan(&get_user_streaks); err != nil {
			return nil, err
		}
		items = append(items, get_user_streaks)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordActivityCompletion = `-- name: RecordActivityCompletion :one
SELECT 
  (result).completion_id::bigint as completion_id,
  (result).points_earned::smallint as points_earned,
  (result).current_streak::smallint as current_streak,
  (result).milestone_achieved::boolean as milestone_achieved,
  COALESCE((result).milestone_bonus::smallint,0)::smallint as milestone_bonus
FROM record_activity_completion($1::uuid, $2::uuid, $3::jsonb) AS result
`

type RecordActivityCompletionParams struct {
	AccountID  uuid.UUID `json:"account_id"`
	ActivityID uuid.UUID `json:"activity_id"`
	Metadata   []byte    `json:"metadata"`
}

type RecordActivityCompletionRow struct {
	CompletionID      int64 `json:"completion_id"`
	PointsEarned      int16 `json:"points_earned"`
	CurrentStreak     int16 `json:"current_streak"`
	MilestoneAchieved bool  `json:"milestone_achieved"`
	MilestoneBonus    int16 `json:"milestone_bonus"`
}

// SELECT *
// FROM record_activity_completion(@account_id::uuid, @activity_id::uuid, @metadata::jsonb);
func (q *Queries) RecordActivityCompletion(ctx context.Context, arg RecordActivityCompletionParams) (RecordActivityCompletionRow, error) {
	row := q.db.QueryRow(ctx, recordActivityCompletion, arg.AccountID, arg.ActivityID, arg.Metadata)
	var i RecordActivityCompletionRow
	err := row.Scan(
		&i.CompletionID,
		&i.PointsEarned,
		&i.CurrentStreak,
		&i.MilestoneAchieved,
		&i.MilestoneBonus,
	)
	return i, err
}
