// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: streaks.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createStreakMilestone = `-- name: CreateStreakMilestone :one
INSERT INTO streak_milestones (
  activity_id, days_required, bonus_points, title, description, is_active
) VALUES ( $1, $2, $3, $4, $5, COALESCE($6::boolean, true) )
RETURNING id, activity_id, days_required, bonus_points, title, description, is_active
`

type CreateStreakMilestoneParams struct {
	ActivityID   *uuid.UUID `json:"activity_id"`
	DaysRequired int16      `json:"days_required"`
	BonusPoints  int16      `json:"bonus_points"`
	Title        string     `json:"title"`
	Description  *string    `json:"description"`
	IsActive     *bool      `json:"is_active"`
}

// Creates a streak milestone.
func (q *Queries) CreateStreakMilestone(ctx context.Context, arg CreateStreakMilestoneParams) (StreakMilestone, error) {
	row := q.db.QueryRow(ctx, createStreakMilestone,
		arg.ActivityID,
		arg.DaysRequired,
		arg.BonusPoints,
		arg.Title,
		arg.Description,
		arg.IsActive,
	)
	var i StreakMilestone
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.DaysRequired,
		&i.BonusPoints,
		&i.Title,
		&i.Description,
		&i.IsActive,
	)
	return i, err
}

const deleteStreakMilestoneByID = `-- name: DeleteStreakMilestoneByID :exec
DELETE FROM streak_milestones WHERE id = $1
`

// Deletes streak milestone by ID
func (q *Queries) DeleteStreakMilestoneByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteStreakMilestoneByID, id)
	return err
}

const getAllActiveStreakMilestoneCount = `-- name: GetAllActiveStreakMilestoneCount :one
SELECT count(id) FROM streak_milestones WHERE is_active = true
`

// Returns all active streak milestones count
func (q *Queries) GetAllActiveStreakMilestoneCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getAllActiveStreakMilestoneCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAllInactiveStreakMilestoneCount = `-- name: GetAllInactiveStreakMilestoneCount :one
SELECT count(id) FROM streak_milestones WHERE is_active = false
`

// Returns all inactive streak milestones count
func (q *Queries) GetAllInactiveStreakMilestoneCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getAllInactiveStreakMilestoneCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAllStreaksMilestoneByActive = `-- name: GetAllStreaksMilestoneByActive :many
SELECT id, activity_id, days_required, bonus_points, title, description, is_active FROM streak_milestones WHERE is_active = $1 
LIMIT $2
OFFSET $3
`

type GetAllStreaksMilestoneByActiveParams struct {
	IsActive bool  `json:"is_active"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

// Returns all streaks by activity status
func (q *Queries) GetAllStreaksMilestoneByActive(ctx context.Context, arg GetAllStreaksMilestoneByActiveParams) ([]StreakMilestone, error) {
	rows, err := q.db.Query(ctx, getAllStreaksMilestoneByActive, arg.IsActive, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StreakMilestone{}
	for rows.Next() {
		var i StreakMilestone
		if err := rows.Scan(
			&i.ID,
			&i.ActivityID,
			&i.DaysRequired,
			&i.BonusPoints,
			&i.Title,
			&i.Description,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserStreaks = `-- name: GetUserStreaks :many
SELECT
  a.name AS activity_name,
  CASE
    WHEN us.last_completion_date < CURRENT_DATE THEN 0::smallint
    ELSE us.current_streak
    END::smallint AS current_streak,
  us.longest_streak,
  us.total_completions,
  us.last_completion_date::text AS last_completion_date,
  COALESCE((
    SELECT MIN(sm.days_required -
      CASE
        WHEN us.last_completion_date < CURRENT_DATE THEN 0
        ELSE us.current_streak
      END)
    FROM streak_milestones sm
    LEFT JOIN user_streak_achievements usa
      ON usa.streak_milestone_id = sm.id AND usa.account_id = us.account_id
    WHERE sm.activity_id = a.id
      AND sm.is_active = true
      AND sm.days_required >
        CASE
          WHEN us.last_completion_date < CURRENT_DATE THEN 0
          ELSE us.current_streak
        END
      AND usa.id IS NULL
  )::smallint, 0)::smallint AS days_until_next_milestone
FROM user_streaks us
JOIN activities a ON a.id = us.activity_id
WHERE us.account_id = $1::uuid
ORDER BY current_streak DESC, a.name ASC
`

type GetUserStreaksRow struct {
	ActivityName           string `json:"activity_name"`
	CurrentStreak          int16  `json:"current_streak"`
	LongestStreak          int16  `json:"longest_streak"`
	TotalCompletions       int32  `json:"total_completions"`
	LastCompletionDate     string `json:"last_completion_date"`
	DaysUntilNextMilestone int16  `json:"days_until_next_milestone"`
}

func (q *Queries) GetUserStreaks(ctx context.Context, accountID uuid.UUID) ([]GetUserStreaksRow, error) {
	rows, err := q.db.Query(ctx, getUserStreaks, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserStreaksRow{}
	for rows.Next() {
		var i GetUserStreaksRow
		if err := rows.Scan(
			&i.ActivityName,
			&i.CurrentStreak,
			&i.LongestStreak,
			&i.TotalCompletions,
			&i.LastCompletionDate,
			&i.DaysUntilNextMilestone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordActivityCompletion = `-- name: RecordActivityCompletion :one
SELECT 
  (result).completion_id::bigint as completion_id,
  (result).points_earned::smallint as points_earned,
  (result).current_streak::smallint as current_streak,
  (result).milestone_achieved::boolean as milestone_achieved,
  COALESCE((result).milestone_bonus::smallint,0)::smallint as milestone_bonus,
  (result).already_processed::boolean as already_processed
FROM record_activity_completion(
  $1::uuid,
  $2::uuid,
  $3::jsonb,
  $4::text,
  $5::text
) AS result
`

type RecordActivityCompletionParams struct {
	AccountID      uuid.UUID `json:"account_id"`
	ActivityID     uuid.UUID `json:"activity_id"`
	Metadata       []byte    `json:"metadata"`
	IdempotencyKey *string   `json:"idempotency_key"`
	AwardedBy      *string   `json:"awarded_by"`
}

type RecordActivityCompletionRow struct {
	CompletionID      int64 `json:"completion_id"`
	PointsEarned      int16 `json:"points_earned"`
	CurrentStreak     int16 `json:"current_streak"`
	MilestoneAchieved bool  `json:"milestone_achieved"`
	MilestoneBonus    int16 `json:"milestone_bonus"`
	AlreadyProcessed  bool  `json:"already_processed"`
}

// Completions can be retried by source event using an optional idempotency key.
func (q *Queries) RecordActivityCompletion(ctx context.Context, arg RecordActivityCompletionParams) (RecordActivityCompletionRow, error) {
	row := q.db.QueryRow(ctx, recordActivityCompletion,
		arg.AccountID,
		arg.ActivityID,
		arg.Metadata,
		arg.IdempotencyKey,
		arg.AwardedBy,
	)
	var i RecordActivityCompletionRow
	err := row.Scan(
		&i.CompletionID,
		&i.PointsEarned,
		&i.CurrentStreak,
		&i.MilestoneAchieved,
		&i.MilestoneBonus,
		&i.AlreadyProcessed,
	)
	return i, err
}
