// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSubscriptionsForPaidOrder = `-- name: CreateSubscriptionsForPaidOrder :exec
WITH paid_order AS (
    SELECT user_id
    FROM public.orders
    WHERE orders.id = $1
      AND orders.status = 'paid'::public.order_status
), plan_items AS (
    SELECT DISTINCT plan_id
    FROM public.order_items
    WHERE order_id = $1
      AND plan_id IS NOT NULL
)
INSERT INTO public.subscriptions (
    user_id,
    plan_id,
    current_period_end
)
SELECT
    paid_order.user_id,
    plan_items.plan_id,
    now() + make_interval(days => plans.billing_interval_days)
FROM paid_order
JOIN plan_items ON true
JOIN public.plans ON plans.id = plan_items.plan_id
ON CONFLICT (user_id) WHERE status = 'active'::public.subscription_status
DO NOTHING
`

// Activate each plan included in a paid order. The partial unique index on
// subscriptions keeps a user from receiving a second simultaneous active plan.
func (q *Queries) CreateSubscriptionsForPaidOrder(ctx context.Context, orderID string) error {
	_, err := q.db.Exec(ctx, createSubscriptionsForPaidOrder, orderID)
	return err
}

const getActiveSubscriptionByUser = `-- name: GetActiveSubscriptionByUser :one
SELECT
    subscriptions.id,
    subscriptions.plan_id,
    plans.code AS plan_code,
    plans.name AS plan_name,
    subscriptions.status,
    subscriptions.started_at,
    subscriptions.current_period_start,
    subscriptions.current_period_end,
    subscriptions.cancel_at_period_end,
    subscriptions.cancelled_at
FROM public.subscriptions
JOIN public.plans ON plans.id = subscriptions.plan_id
WHERE subscriptions.user_id = $1
  AND subscriptions.status = 'active'::public.subscription_status
  AND (
      subscriptions.current_period_end IS NULL
      OR subscriptions.current_period_end > now()
  )
ORDER BY subscriptions.started_at DESC
LIMIT 1
`

type GetActiveSubscriptionByUserRow struct {
	ID                 int64              `json:"id"`
	PlanID             int64              `json:"plan_id"`
	PlanCode           string             `json:"plan_code"`
	PlanName           string             `json:"plan_name"`
	Status             SubscriptionStatus `json:"status"`
	StartedAt          time.Time          `json:"started_at"`
	CurrentPeriodStart time.Time          `json:"current_period_start"`
	CurrentPeriodEnd   *time.Time         `json:"current_period_end"`
	CancelAtPeriodEnd  bool               `json:"cancel_at_period_end"`
	CancelledAt        *time.Time         `json:"cancelled_at"`
}

// Retrieves the caller's currently valid active subscription and its plan.
func (q *Queries) GetActiveSubscriptionByUser(ctx context.Context, userID uuid.UUID) (GetActiveSubscriptionByUserRow, error) {
	row := q.db.QueryRow(ctx, getActiveSubscriptionByUser, userID)
	var i GetActiveSubscriptionByUserRow
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.PlanCode,
		&i.PlanName,
		&i.Status,
		&i.StartedAt,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CancelledAt,
	)
	return i, err
}
