// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const recordIssuedRefreshToken = `-- name: RecordIssuedRefreshToken :one
INSERT INTO refresh_tokens (
  token_hash, user_id, device_id, jwt_jti, issued_at, family_id
)
VALUES($1, $2, $3, $4, $5, $6)
RETURNING id, token_hash, user_id, device_id, jwt_jti, issued_at, expires_at, used_at, revoked_at, replaced_by, family_id
`

type RecordIssuedRefreshTokenParams struct {
	TokenHash string           `json:"token_hash"`
	UserID    uuid.UUID        `json:"user_id"`
	DeviceID  pgtype.UUID      `json:"device_id"`
	JwtJti    pgtype.UUID      `json:"jwt_jti"`
	IssuedAt  pgtype.Timestamp `json:"issued_at"`
	FamilyID  uuid.UUID        `json:"family_id"`
}

// Persists an issued refresh token's information to the db
func (q *Queries) RecordIssuedRefreshToken(ctx context.Context, arg RecordIssuedRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, recordIssuedRefreshToken,
		arg.TokenHash,
		arg.UserID,
		arg.DeviceID,
		arg.JwtJti,
		arg.IssuedAt,
		arg.FamilyID,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.DeviceID,
		&i.JwtJti,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.ReplacedBy,
		&i.FamilyID,
	)
	return i, err
}

const recordIssuedToken = `-- name: RecordIssuedToken :one
INSERT INTO issued_tokens (
  jti, user_id, device_id, expires_at
) VALUES ( $1, $2, $3, $4 )
RETURNING id, jti, user_id, device_id, issued_at, expires_at, revoked_at, last_used_at
`

type RecordIssuedTokenParams struct {
	Jti       uuid.UUID        `json:"jti"`
	UserID    uuid.UUID        `json:"user_id"`
	DeviceID  pgtype.UUID      `json:"device_id"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

// Records an issued access token's information to the db
func (q *Queries) RecordIssuedToken(ctx context.Context, arg RecordIssuedTokenParams) (IssuedToken, error) {
	row := q.db.QueryRow(ctx, recordIssuedToken,
		arg.Jti,
		arg.UserID,
		arg.DeviceID,
		arg.ExpiresAt,
	)
	var i IssuedToken
	err := row.Scan(
		&i.ID,
		&i.Jti,
		&i.UserID,
		&i.DeviceID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
	)
	return i, err
}
