// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimRefreshToken = `-- name: ClaimRefreshToken :one
UPDATE refresh_tokens
SET used_at = NOW()
WHERE token_hash = $1
  AND used_at    IS NULL
  AND revoked_at IS NULL
  AND expires_at > NOW()
RETURNING id, token_hash, user_id, device_id, jwt_jti, issued_at, expires_at, used_at, revoked_at, replaced_by, family_id
`

func (q *Queries) ClaimRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, claimRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.DeviceID,
		&i.JwtJti,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.ReplacedBy,
		&i.FamilyID,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, token_hash, user_id, device_id, jwt_jti, issued_at, expires_at, used_at, revoked_at, replaced_by, family_id FROM refresh_tokens WHERE token_hash = $1 LIMIT 1
`

// Retrieves an earlier issued refresh token given its hash
func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.DeviceID,
		&i.JwtJti,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.ReplacedBy,
		&i.FamilyID,
	)
	return i, err
}

const markRefreshTokenUsed = `-- name: MarkRefreshTokenUsed :exec
UPDATE refresh_tokens
  SET 
    used_at = NOW(),
    revoked_at = NOW()
  WHERE id = $1
`

// Marks and persists that a refresh token has been used
func (q *Queries) MarkRefreshTokenUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markRefreshTokenUsed, id)
	return err
}

const recordIssuedRefreshToken = `-- name: RecordIssuedRefreshToken :one
INSERT INTO refresh_tokens (
  token_hash, user_id, device_id, jwt_jti, issued_at, expires_at, family_id
)
VALUES($1, $2, $3, $4, $5, $6, $7)
RETURNING id, token_hash, user_id, device_id, jwt_jti, issued_at, expires_at, used_at, revoked_at, replaced_by, family_id
`

type RecordIssuedRefreshTokenParams struct {
	TokenHash string           `json:"token_hash"`
	UserID    uuid.UUID        `json:"user_id"`
	DeviceID  pgtype.UUID      `json:"device_id"`
	JwtJti    pgtype.UUID      `json:"jwt_jti"`
	IssuedAt  pgtype.Timestamp `json:"issued_at"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	FamilyID  uuid.UUID        `json:"family_id"`
}

// Persists an issued refresh token's information to the db
func (q *Queries) RecordIssuedRefreshToken(ctx context.Context, arg RecordIssuedRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, recordIssuedRefreshToken,
		arg.TokenHash,
		arg.UserID,
		arg.DeviceID,
		arg.JwtJti,
		arg.IssuedAt,
		arg.ExpiresAt,
		arg.FamilyID,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.DeviceID,
		&i.JwtJti,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.ReplacedBy,
		&i.FamilyID,
	)
	return i, err
}

const recordIssuedToken = `-- name: RecordIssuedToken :one
INSERT INTO issued_tokens (
  jti, user_id, device_id, expires_at
) VALUES ( $1, $2, $3, $4 )
RETURNING id, jti, user_id, device_id, issued_at, expires_at, revoked_at, last_used_at
`

type RecordIssuedTokenParams struct {
	Jti       uuid.UUID        `json:"jti"`
	UserID    uuid.UUID        `json:"user_id"`
	DeviceID  pgtype.UUID      `json:"device_id"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

// Records an issued access token's information to the db
func (q *Queries) RecordIssuedToken(ctx context.Context, arg RecordIssuedTokenParams) (IssuedToken, error) {
	row := q.db.QueryRow(ctx, recordIssuedToken,
		arg.Jti,
		arg.UserID,
		arg.DeviceID,
		arg.ExpiresAt,
	)
	var i IssuedToken
	err := row.Scan(
		&i.ID,
		&i.Jti,
		&i.UserID,
		&i.DeviceID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const revokeRefreshTokenFamily = `-- name: RevokeRefreshTokenFamily :exec
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE family_id = $1
  AND revoked_at IS NULL
`

// RevokeRefreshTokenFamily revokes all active refresh tokens belonging to a given family.
// This is triggered when a refresh token reuse attack is detected — i.e. a token that
// has already been used is presented again. Revoking the entire family forces the user
// to re-authenticate, invalidating any tokens the attacker may have obtained.
func (q *Queries) RevokeRefreshTokenFamily(ctx context.Context, familyID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenFamily, familyID)
	return err
}
