// Code generated by MockGen. DO NOT EDIT.
// Source: publishers.go
//
// Generated by this command:
//
//	mockgen -source=publishers.go -destination=mocks/publishers.go -package=mockeventbus
//

// Package mockeventbus is a generated GoMock package.
package mockeventbus

import (
	context "context"
	reflect "reflect"

	eventbus "github.com/opencrafts-io/verisafe/internal/eventbus"
	repository "github.com/opencrafts-io/verisafe/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockUserPublisher is a mock of UserPublisher interface.
type MockUserPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockUserPublisherMockRecorder
	isgomock struct{}
}

// MockUserPublisherMockRecorder is the mock recorder for MockUserPublisher.
type MockUserPublisherMockRecorder struct {
	mock *MockUserPublisher
}

// NewMockUserPublisher creates a new mock instance.
func NewMockUserPublisher(ctrl *gomock.Controller) *MockUserPublisher {
	mock := &MockUserPublisher{ctrl: ctrl}
	mock.recorder = &MockUserPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserPublisher) EXPECT() *MockUserPublisherMockRecorder {
	return m.recorder
}

// PublishUserCreated mocks base method.
func (m *MockUserPublisher) PublishUserCreated(ctx context.Context, user repository.Account, requestID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishUserCreated", ctx, user, requestID)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishUserCreated indicates an expected call of PublishUserCreated.
func (mr *MockUserPublisherMockRecorder) PublishUserCreated(ctx, user, requestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishUserCreated", reflect.TypeOf((*MockUserPublisher)(nil).PublishUserCreated), ctx, user, requestID)
}

// PublishUserDeleted mocks base method.
func (m *MockUserPublisher) PublishUserDeleted(ctx context.Context, user repository.Account, requestID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishUserDeleted", ctx, user, requestID)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishUserDeleted indicates an expected call of PublishUserDeleted.
func (mr *MockUserPublisherMockRecorder) PublishUserDeleted(ctx, user, requestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishUserDeleted", reflect.TypeOf((*MockUserPublisher)(nil).PublishUserDeleted), ctx, user, requestID)
}

// PublishUserUpdated mocks base method.
func (m *MockUserPublisher) PublishUserUpdated(ctx context.Context, user repository.Account, requestID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishUserUpdated", ctx, user, requestID)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishUserUpdated indicates an expected call of PublishUserUpdated.
func (mr *MockUserPublisherMockRecorder) PublishUserUpdated(ctx, user, requestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishUserUpdated", reflect.TypeOf((*MockUserPublisher)(nil).PublishUserUpdated), ctx, user, requestID)
}

// MockInstitutionPublisher is a mock of InstitutionPublisher interface.
type MockInstitutionPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockInstitutionPublisherMockRecorder
	isgomock struct{}
}

// MockInstitutionPublisherMockRecorder is the mock recorder for MockInstitutionPublisher.
type MockInstitutionPublisherMockRecorder struct {
	mock *MockInstitutionPublisher
}

// NewMockInstitutionPublisher creates a new mock instance.
func NewMockInstitutionPublisher(ctrl *gomock.Controller) *MockInstitutionPublisher {
	mock := &MockInstitutionPublisher{ctrl: ctrl}
	mock.recorder = &MockInstitutionPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInstitutionPublisher) EXPECT() *MockInstitutionPublisherMockRecorder {
	return m.recorder
}

// PublishInstitutionCreated mocks base method.
func (m *MockInstitutionPublisher) PublishInstitutionCreated(ctx context.Context, institution repository.Institution, requestID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishInstitutionCreated", ctx, institution, requestID)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishInstitutionCreated indicates an expected call of PublishInstitutionCreated.
func (mr *MockInstitutionPublisherMockRecorder) PublishInstitutionCreated(ctx, institution, requestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishInstitutionCreated", reflect.TypeOf((*MockInstitutionPublisher)(nil).PublishInstitutionCreated), ctx, institution, requestID)
}

// PublishInstitutionDeleted mocks base method.
func (m *MockInstitutionPublisher) PublishInstitutionDeleted(ctx context.Context, institution repository.Institution, requestID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishInstitutionDeleted", ctx, institution, requestID)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishInstitutionDeleted indicates an expected call of PublishInstitutionDeleted.
func (mr *MockInstitutionPublisherMockRecorder) PublishInstitutionDeleted(ctx, institution, requestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishInstitutionDeleted", reflect.TypeOf((*MockInstitutionPublisher)(nil).PublishInstitutionDeleted), ctx, institution, requestID)
}

// PublishInstitutionUpdated mocks base method.
func (m *MockInstitutionPublisher) PublishInstitutionUpdated(ctx context.Context, institution repository.Institution, requestID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishInstitutionUpdated", ctx, institution, requestID)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishInstitutionUpdated indicates an expected call of PublishInstitutionUpdated.
func (mr *MockInstitutionPublisherMockRecorder) PublishInstitutionUpdated(ctx, institution, requestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishInstitutionUpdated", reflect.TypeOf((*MockInstitutionPublisher)(nil).PublishInstitutionUpdated), ctx, institution, requestID)
}

// MockNotificationPublisher is a mock of NotificationPublisher interface.
type MockNotificationPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationPublisherMockRecorder
	isgomock struct{}
}

// MockNotificationPublisherMockRecorder is the mock recorder for MockNotificationPublisher.
type MockNotificationPublisherMockRecorder struct {
	mock *MockNotificationPublisher
}

// NewMockNotificationPublisher creates a new mock instance.
func NewMockNotificationPublisher(ctrl *gomock.Controller) *MockNotificationPublisher {
	mock := &MockNotificationPublisher{ctrl: ctrl}
	mock.recorder = &MockNotificationPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationPublisher) EXPECT() *MockNotificationPublisherMockRecorder {
	return m.recorder
}

// PublishPushNotificationRequested mocks base method.
func (m *MockNotificationPublisher) PublishPushNotificationRequested(ctx context.Context, notification eventbus.NotificationPayload, requestID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishPushNotificationRequested", ctx, notification, requestID)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishPushNotificationRequested indicates an expected call of PublishPushNotificationRequested.
func (mr *MockNotificationPublisherMockRecorder) PublishPushNotificationRequested(ctx, notification, requestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishPushNotificationRequested", reflect.TypeOf((*MockNotificationPublisher)(nil).PublishPushNotificationRequested), ctx, notification, requestID)
}
